// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package pccs.vehiclestates.services.battery.v1.battery_service

@SerialVersionUID(0L)
final case class GetBatteryResponse(
  id: _root_.scala.Predef.String = "",
  vin: _root_.scala.Predef.String = "",
  battery: _root_.scala.Option[pccs.vehiclestates.entities.battery.v1.battery.Battery] =
    _root_.scala.None,
  unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
) extends scalapb.GeneratedMessage
  with scalapb.lenses.Updatable[GetBatteryResponse]:
  @transient
  private var __serializedSizeMemoized: _root_.scala.Int = 0
  private def __computeSerializedSize(): _root_.scala.Int =
    var __size = 0

    {
      val __value = id
      if !__value.isEmpty then
        __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
    };

    {
      val __value = vin
      if !__value.isEmpty then
        __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
    };
    if battery.isDefined then
      val __value = battery.get
      __size += 1 + _root_.com.google.protobuf.CodedOutputStream
        .computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize;
    __size += unknownFields.serializedSize
    __size
  override def serializedSize: _root_.scala.Int =
    var __size = __serializedSizeMemoized
    if __size == 0 then
      __size = __computeSerializedSize() + 1
      __serializedSizeMemoized = __size
    __size - 1

  def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit =
    {
      val __v = id
      if !__v.isEmpty then _output__.writeString(1, __v)
    };
    {
      val __v = vin
      if !__v.isEmpty then _output__.writeString(2, __v)
    };
    battery.foreach: __v =>
      val __m = __v
      _output__.writeTag(3, 2)
      _output__.writeUInt32NoTag(__m.serializedSize)
      __m.writeTo(_output__)
    ;
    unknownFields.writeTo(_output__)
  def withId(__v: _root_.scala.Predef.String): GetBatteryResponse = copy(id = __v)
  def withVin(__v: _root_.scala.Predef.String): GetBatteryResponse = copy(vin = __v)
  def getBattery: pccs.vehiclestates.entities.battery.v1.battery.Battery =
    battery.getOrElse(pccs.vehiclestates.entities.battery.v1.battery.Battery.defaultInstance)
  def clearBattery: GetBatteryResponse = copy(battery = _root_.scala.None)
  def withBattery(__v: pccs.vehiclestates.entities.battery.v1.battery.Battery): GetBatteryResponse =
    copy(battery = Option(__v))
  def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
  def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
  def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any =
    (__fieldNumber: @ _root_.scala.unchecked) match
      case 1 =>
        val __t = id
        if __t != "" then __t else null
      case 2 =>
        val __t = vin
        if __t != "" then __t else null
      case 3 => battery.orNull
  def getField(
    __field: _root_.scalapb.descriptors.FieldDescriptor
  ): _root_.scalapb.descriptors.PValue =
    _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
    (__field.number: @ _root_.scala.unchecked) match
      case 1 => _root_.scalapb.descriptors.PString(id)
      case 2 => _root_.scalapb.descriptors.PString(vin)
      case 3 => battery.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
  def toProtoString: _root_.scala.Predef.String =
    _root_.scalapb.TextFormat.printToUnicodeString(this)
  def companion: pccs.vehiclestates.services.battery.v1.battery_service.GetBatteryResponse.type =
    pccs.vehiclestates.services.battery.v1.battery_service.GetBatteryResponse
  // @@protoc_insertion_point(GeneratedMessage[pccs.vehiclestates.services.battery.v1.GetBatteryResponse])

object GetBatteryResponse
  extends scalapb.GeneratedMessageCompanion[
    pccs.vehiclestates.services.battery.v1.battery_service.GetBatteryResponse
  ]:
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[
    pccs.vehiclestates.services.battery.v1.battery_service.GetBatteryResponse
  ] = this
  def parseFrom(
    `_input__`: _root_.com.google.protobuf.CodedInputStream
  ): pccs.vehiclestates.services.battery.v1.battery_service.GetBatteryResponse =
    var __id: _root_.scala.Predef.String = ""
    var __vin: _root_.scala.Predef.String = ""
    var __battery: _root_.scala.Option[pccs.vehiclestates.entities.battery.v1.battery.Battery] =
      _root_.scala.None
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while !_done__ do
      val _tag__ = _input__.readTag()
      _tag__ match
        case 0  => _done__ = true
        case 10 =>
          __id = _input__.readStringRequireUtf8()
        case 18 =>
          __vin = _input__.readStringRequireUtf8()
        case 26 =>
          __battery = _root_.scala.Option(
            __battery.fold(
              _root_.scalapb.LiteParser
                .readMessage[pccs.vehiclestates.entities.battery.v1.battery.Battery](_input__)
            )(_root_.scalapb.LiteParser.readMessage(_input__, _))
          )
        case tag =>
          if _unknownFields__ == null then
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          _unknownFields__.parseField(tag, _input__)
    pccs.vehiclestates.services.battery.v1.battery_service.GetBatteryResponse(
      id = __id,
      vin = __vin,
      battery = __battery,
      unknownFields = if _unknownFields__ == null then _root_.scalapb.UnknownFieldSet.empty
      else _unknownFields__.result()
    )
  implicit def messageReads: _root_.scalapb.descriptors.Reads[
    pccs.vehiclestates.services.battery.v1.battery_service.GetBatteryResponse
  ] = _root_.scalapb.descriptors.Reads:
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(
        __fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor),
        "FieldDescriptor does not match message type."
      )
      pccs.vehiclestates.services.battery.v1.battery_service.GetBatteryResponse(
        id = __fieldsMap
          .get(scalaDescriptor.findFieldByNumber(1).get)
          .map(_.as[_root_.scala.Predef.String])
          .getOrElse(""),
        vin = __fieldsMap
          .get(scalaDescriptor.findFieldByNumber(2).get)
          .map(_.as[_root_.scala.Predef.String])
          .getOrElse(""),
        battery = __fieldsMap
          .get(scalaDescriptor.findFieldByNumber(3).get)
          .flatMap(
            _.as[_root_.scala.Option[pccs.vehiclestates.entities.battery.v1.battery.Battery]]
          )
      )
    case _ => throw new RuntimeException("Expected PMessage")
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor =
    pccs.vehiclestates.services.battery.v1.battery_service.BatteryServiceProto.javaDescriptor
      .getMessageTypes()
      .get(1)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor =
    pccs.vehiclestates.services.battery.v1.battery_service.BatteryServiceProto.scalaDescriptor
      .messages(1)
  def messageCompanionForFieldNumber(
    __number: _root_.scala.Int
  ): _root_.scalapb.GeneratedMessageCompanion[?] =
    var __out: _root_.scalapb.GeneratedMessageCompanion[?] = null
    (__number: @ _root_.scala.unchecked) match
      case 3 => __out = pccs.vehiclestates.entities.battery.v1.battery.Battery
    __out
  lazy val nestedMessagesCompanions
    : Seq[_root_.scalapb.GeneratedMessageCompanion[? <: _root_.scalapb.GeneratedMessage]] =
    Seq.empty
  def enumCompanionForFieldNumber(
    __fieldNumber: _root_.scala.Int
  ): _root_.scalapb.GeneratedEnumCompanion[?] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance =
    pccs.vehiclestates.services.battery.v1.battery_service.GetBatteryResponse(
      id = "",
      vin = "",
      battery = _root_.scala.None
    )
  implicit class GetBatteryResponseLens[UpperPB](
    _l: _root_.scalapb.lenses.Lens[
      UpperPB,
      pccs.vehiclestates.services.battery.v1.battery_service.GetBatteryResponse
    ]
  ) extends _root_.scalapb.lenses.ObjectLens[
      UpperPB,
      pccs.vehiclestates.services.battery.v1.battery_service.GetBatteryResponse
    ](_l):
    def id: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] =
      field(_.id)((c_, f_) => c_.copy(id = f_))
    def vin: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] =
      field(_.vin)((c_, f_) => c_.copy(vin = f_))
    def battery: _root_.scalapb.lenses.Lens[
      UpperPB,
      pccs.vehiclestates.entities.battery.v1.battery.Battery
    ] = field(_.getBattery)((c_, f_) => c_.copy(battery = _root_.scala.Option(f_)))
    def optionalBattery: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[
      pccs.vehiclestates.entities.battery.v1.battery.Battery
    ]] = field(_.battery)((c_, f_) => c_.copy(battery = f_))
  final val ID_FIELD_NUMBER = 1
  final val VIN_FIELD_NUMBER = 2
  final val BATTERY_FIELD_NUMBER = 3
  def of(
    id: _root_.scala.Predef.String,
    vin: _root_.scala.Predef.String,
    battery: _root_.scala.Option[pccs.vehiclestates.entities.battery.v1.battery.Battery]
  ): _root_.pccs.vehiclestates.services.battery.v1.battery_service.GetBatteryResponse =
    _root_.pccs.vehiclestates.services.battery.v1.battery_service.GetBatteryResponse(
      id,
      vin,
      battery
    )
  // @@protoc_insertion_point(GeneratedMessageCompanion[pccs.vehiclestates.services.battery.v1.GetBatteryResponse])
