// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package pccs.chronos.messages.targetsoc.v1.target_soc

@SerialVersionUID(0L)
final case class SetTargetSocRequest(
  request: _root_.scala.Option[pccs.chronos.messages.common.v1.chronos_request.ChronosRequest] =
    _root_.scala.None,
  batteryChargeTargetLevel: _root_.scala.Int = 0,
  chargeTargetLevelSettingType: pccs.chronos.messages.targetsoc.v1.target_soc.ChargeTargetLevelSettingType =
    pccs.chronos.messages.targetsoc.v1.target_soc.ChargeTargetLevelSettingType.CHARGE_TARGET_LEVEL_SETTING_TYPE_UNSPECIFIED,
  unknownFields: scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
) extends scalapb.GeneratedMessage
  with scalapb.lenses.Updatable[SetTargetSocRequest]:
  @transient
  private var __serializedSizeMemoized: _root_.scala.Int = 0
  private def __computeSerializedSize(): _root_.scala.Int =
    var __size = 0
    if request.isDefined then
      val __value = request.get
      __size += 1 + _root_.com.google.protobuf.CodedOutputStream
        .computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize;

    {
      val __value = batteryChargeTargetLevel
      if __value != 0 then
        __size += _root_.com.google.protobuf.CodedOutputStream.computeInt32Size(2, __value)
    };

    {
      val __value = chargeTargetLevelSettingType.value
      if __value != 0 then
        __size += _root_.com.google.protobuf.CodedOutputStream.computeEnumSize(3, __value)
    };
    __size += unknownFields.serializedSize
    __size
  override def serializedSize: _root_.scala.Int =
    var __size = __serializedSizeMemoized
    if __size == 0 then
      __size = __computeSerializedSize() + 1
      __serializedSizeMemoized = __size
    __size - 1

  def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit =
    request.foreach: __v =>
      val __m = __v
      _output__.writeTag(1, 2)
      _output__.writeUInt32NoTag(__m.serializedSize)
      __m.writeTo(_output__)
    ;
    {
      val __v = batteryChargeTargetLevel
      if __v != 0 then _output__.writeInt32(2, __v)
    };
    {
      val __v = chargeTargetLevelSettingType.value
      if __v != 0 then _output__.writeEnum(3, __v)
    };
    unknownFields.writeTo(_output__)
  def getRequest: pccs.chronos.messages.common.v1.chronos_request.ChronosRequest =
    request.getOrElse(
      pccs.chronos.messages.common.v1.chronos_request.ChronosRequest.defaultInstance
    )
  def clearRequest: SetTargetSocRequest = copy(request = _root_.scala.None)
  def withRequest(
    __v: pccs.chronos.messages.common.v1.chronos_request.ChronosRequest
  ): SetTargetSocRequest = copy(request = Option(__v))
  def withBatteryChargeTargetLevel(__v: _root_.scala.Int): SetTargetSocRequest =
    copy(batteryChargeTargetLevel = __v)
  def withChargeTargetLevelSettingType(
    __v: pccs.chronos.messages.targetsoc.v1.target_soc.ChargeTargetLevelSettingType
  ): SetTargetSocRequest = copy(chargeTargetLevelSettingType = __v)
  def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
  def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
  def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any =
    (__fieldNumber: @ _root_.scala.unchecked) match
      case 1 => request.orNull
      case 2 =>
        val __t = batteryChargeTargetLevel
        if __t != 0 then __t else null
      case 3 =>
        val __t = chargeTargetLevelSettingType.javaValueDescriptor
        if __t.getNumber() != 0 then __t else null
  def getField(
    __field: _root_.scalapb.descriptors.FieldDescriptor
  ): _root_.scalapb.descriptors.PValue =
    _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
    (__field.number: @ _root_.scala.unchecked) match
      case 1 => request.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
      case 2 => _root_.scalapb.descriptors.PInt(batteryChargeTargetLevel)
      case 3 => _root_.scalapb.descriptors.PEnum(chargeTargetLevelSettingType.scalaValueDescriptor)
  def toProtoString: _root_.scala.Predef.String =
    _root_.scalapb.TextFormat.printToUnicodeString(this)
  def companion: pccs.chronos.messages.targetsoc.v1.target_soc.SetTargetSocRequest.type =
    pccs.chronos.messages.targetsoc.v1.target_soc.SetTargetSocRequest
  // @@protoc_insertion_point(GeneratedMessage[pccs.chronos.messages.targetsoc.v1.SetTargetSocRequest])

object SetTargetSocRequest
  extends scalapb.GeneratedMessageCompanion[
    pccs.chronos.messages.targetsoc.v1.target_soc.SetTargetSocRequest
  ]:
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[
    pccs.chronos.messages.targetsoc.v1.target_soc.SetTargetSocRequest
  ] = this
  def parseFrom(
    `_input__`: _root_.com.google.protobuf.CodedInputStream
  ): pccs.chronos.messages.targetsoc.v1.target_soc.SetTargetSocRequest =
    var __request
      : _root_.scala.Option[pccs.chronos.messages.common.v1.chronos_request.ChronosRequest] =
      _root_.scala.None
    var __batteryChargeTargetLevel: _root_.scala.Int = 0
    var __chargeTargetLevelSettingType
      : pccs.chronos.messages.targetsoc.v1.target_soc.ChargeTargetLevelSettingType =
      pccs.chronos.messages.targetsoc.v1.target_soc.ChargeTargetLevelSettingType.CHARGE_TARGET_LEVEL_SETTING_TYPE_UNSPECIFIED
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while !_done__ do
      val _tag__ = _input__.readTag()
      _tag__ match
        case 0  => _done__ = true
        case 10 =>
          __request = _root_.scala.Option(
            __request.fold(
              _root_.scalapb.LiteParser
                .readMessage[pccs.chronos.messages.common.v1.chronos_request.ChronosRequest](
                  _input__
                )
            )(_root_.scalapb.LiteParser.readMessage(_input__, _))
          )
        case 16 =>
          __batteryChargeTargetLevel = _input__.readInt32()
        case 24 =>
          __chargeTargetLevelSettingType =
            pccs.chronos.messages.targetsoc.v1.target_soc.ChargeTargetLevelSettingType
              .fromValue(_input__.readEnum())
        case tag =>
          if _unknownFields__ == null then
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          _unknownFields__.parseField(tag, _input__)
    pccs.chronos.messages.targetsoc.v1.target_soc.SetTargetSocRequest(
      request = __request,
      batteryChargeTargetLevel = __batteryChargeTargetLevel,
      chargeTargetLevelSettingType = __chargeTargetLevelSettingType,
      unknownFields = if _unknownFields__ == null then _root_.scalapb.UnknownFieldSet.empty
      else _unknownFields__.result()
    )
  implicit def messageReads: _root_.scalapb.descriptors.Reads[
    pccs.chronos.messages.targetsoc.v1.target_soc.SetTargetSocRequest
  ] = _root_.scalapb.descriptors.Reads:
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(
        __fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor),
        "FieldDescriptor does not match message type."
      )
      pccs.chronos.messages.targetsoc.v1.target_soc.SetTargetSocRequest(
        request = __fieldsMap
          .get(scalaDescriptor.findFieldByNumber(1).get)
          .flatMap(
            _.as[
              _root_.scala.Option[pccs.chronos.messages.common.v1.chronos_request.ChronosRequest]
            ]
          ),
        batteryChargeTargetLevel = __fieldsMap
          .get(scalaDescriptor.findFieldByNumber(2).get)
          .map(_.as[_root_.scala.Int])
          .getOrElse(0),
        chargeTargetLevelSettingType =
          pccs.chronos.messages.targetsoc.v1.target_soc.ChargeTargetLevelSettingType.fromValue(
            __fieldsMap
              .get(scalaDescriptor.findFieldByNumber(3).get)
              .map(_.as[_root_.scalapb.descriptors.EnumValueDescriptor])
              .getOrElse(
                pccs.chronos.messages.targetsoc.v1.target_soc.ChargeTargetLevelSettingType.CHARGE_TARGET_LEVEL_SETTING_TYPE_UNSPECIFIED.scalaValueDescriptor
              )
              .number
          )
      )
    case _ => throw new RuntimeException("Expected PMessage")
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor =
    pccs.chronos.messages.targetsoc.v1.target_soc.TargetSocProto.javaDescriptor
      .getMessageTypes()
      .get(3)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor =
    pccs.chronos.messages.targetsoc.v1.target_soc.TargetSocProto.scalaDescriptor.messages(3)
  def messageCompanionForFieldNumber(
    __number: _root_.scala.Int
  ): _root_.scalapb.GeneratedMessageCompanion[?] =
    var __out: _root_.scalapb.GeneratedMessageCompanion[?] = null
    (__number: @ _root_.scala.unchecked) match
      case 1 => __out = pccs.chronos.messages.common.v1.chronos_request.ChronosRequest
    __out
  lazy val nestedMessagesCompanions
    : Seq[_root_.scalapb.GeneratedMessageCompanion[? <: _root_.scalapb.GeneratedMessage]] =
    Seq.empty
  def enumCompanionForFieldNumber(
    __fieldNumber: _root_.scala.Int
  ): _root_.scalapb.GeneratedEnumCompanion[?] =
    (__fieldNumber: @ _root_.scala.unchecked) match
      case 3 => pccs.chronos.messages.targetsoc.v1.target_soc.ChargeTargetLevelSettingType
  lazy val defaultInstance = pccs.chronos.messages.targetsoc.v1.target_soc.SetTargetSocRequest(
    request = _root_.scala.None,
    batteryChargeTargetLevel = 0,
    chargeTargetLevelSettingType =
      pccs.chronos.messages.targetsoc.v1.target_soc.ChargeTargetLevelSettingType.CHARGE_TARGET_LEVEL_SETTING_TYPE_UNSPECIFIED
  )
  implicit class SetTargetSocRequestLens[UpperPB](
    _l: _root_.scalapb.lenses.Lens[
      UpperPB,
      pccs.chronos.messages.targetsoc.v1.target_soc.SetTargetSocRequest
    ]
  ) extends _root_.scalapb.lenses.ObjectLens[
      UpperPB,
      pccs.chronos.messages.targetsoc.v1.target_soc.SetTargetSocRequest
    ](_l):
    def request: _root_.scalapb.lenses.Lens[
      UpperPB,
      pccs.chronos.messages.common.v1.chronos_request.ChronosRequest
    ] = field(_.getRequest)((c_, f_) => c_.copy(request = _root_.scala.Option(f_)))
    def optionalRequest: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[
      pccs.chronos.messages.common.v1.chronos_request.ChronosRequest
    ]] = field(_.request)((c_, f_) => c_.copy(request = f_))
    def batteryChargeTargetLevel: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Int] =
      field(_.batteryChargeTargetLevel)((c_, f_) => c_.copy(batteryChargeTargetLevel = f_))
    def chargeTargetLevelSettingType: _root_.scalapb.lenses.Lens[
      UpperPB,
      pccs.chronos.messages.targetsoc.v1.target_soc.ChargeTargetLevelSettingType
    ] =
      field(_.chargeTargetLevelSettingType)((c_, f_) => c_.copy(chargeTargetLevelSettingType = f_))
  final val REQUEST_FIELD_NUMBER = 1
  final val BATTERY_CHARGE_TARGET_LEVEL_FIELD_NUMBER = 2
  final val CHARGE_TARGET_LEVEL_SETTING_TYPE_FIELD_NUMBER = 3
  def of(
    request: _root_.scala.Option[pccs.chronos.messages.common.v1.chronos_request.ChronosRequest],
    batteryChargeTargetLevel: _root_.scala.Int,
    chargeTargetLevelSettingType: pccs.chronos.messages.targetsoc.v1.target_soc.ChargeTargetLevelSettingType
  ): _root_.pccs.chronos.messages.targetsoc.v1.target_soc.SetTargetSocRequest =
    _root_.pccs.chronos.messages.targetsoc.v1.target_soc.SetTargetSocRequest(
      request,
      batteryChargeTargetLevel,
      chargeTargetLevelSettingType
    )
  // @@protoc_insertion_point(GeneratedMessageCompanion[pccs.chronos.messages.targetsoc.v1.SetTargetSocRequest])
