// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package pccs.chronos.messages.targetsoc.v1.target_soc

object TargetSocProto extends _root_.scalapb.GeneratedFileObject:
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    pccs.chronos.messages.common.v1.chronos_request.ChronosRequestProto
  )
  lazy val messagesCompanions
    : Seq[_root_.scalapb.GeneratedMessageCompanion[? <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[? <: _root_.scalapb.GeneratedMessage]](
      pccs.chronos.messages.targetsoc.v1.target_soc.TargetSoc,
      pccs.chronos.messages.targetsoc.v1.target_soc.GetTargetSocRequest,
      pccs.chronos.messages.targetsoc.v1.target_soc.GetTargetSocResponse,
      pccs.chronos.messages.targetsoc.v1.target_soc.SetTargetSocRequest,
      pccs.chronos.messages.targetsoc.v1.target_soc.SetTargetSocResponse
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
    scalapb.Encoding.fromBase64(
      scala.collection.immutable
        .Seq(
          """ChB0YXJnZXRfc29jLnByb3RvEiJwY2NzLmNocm9ub3MubWVzc2FnZXMudGFyZ2V0c29jLnYxGhVjaHJvbm9zX3JlcXVlc3Quc
  HJvdG8ihAMKCVRhcmdldFNvYxJcChtiYXR0ZXJ5X2NoYXJnZV90YXJnZXRfbGV2ZWwYASABKAVCHeI/GhIYYmF0dGVyeUNoYXJnZ
  VRhcmdldExldmVsUhhiYXR0ZXJ5Q2hhcmdlVGFyZ2V0TGV2ZWwSqwEKIGNoYXJnZV90YXJnZXRfbGV2ZWxfc2V0dGluZ190eXBlG
  AIgASgOMkAucGNjcy5jaHJvbm9zLm1lc3NhZ2VzLnRhcmdldHNvYy52MS5DaGFyZ2VUYXJnZXRMZXZlbFNldHRpbmdUeXBlQiHiP
  x4SHGNoYXJnZVRhcmdldExldmVsU2V0dGluZ1R5cGVSHGNoYXJnZVRhcmdldExldmVsU2V0dGluZ1R5cGUSLQoKdXBkYXRlZF9hd
  BgDIAEoA0IO4j8LEgl1cGRhdGVkQXRSCXVwZGF0ZWRBdBIjCgZzb3VyY2UYBCABKAlCC+I/CBIGc291cmNlUgZzb3VyY2USFwoCa
  WQYBSABKAlCB+I/BBICaWRSAmlkIm4KE0dldFRhcmdldFNvY1JlcXVlc3QSVwoHcmVxdWVzdBgBIAEoCzIvLnBjY3MuY2hyb25vc
  y5tZXNzYWdlcy5jb21tb24udjEuQ2hyb25vc1JlcXVlc3RCDOI/CRIHcmVxdWVzdFIHcmVxdWVzdCLgAgoUR2V0VGFyZ2V0U29jU
  mVzcG9uc2USFwoCaWQYASABKAlCB+I/BBICaWRSAmlkEhoKA3ZpbhgCIAEoCUII4j8FEgN2aW5SA3ZpbhJcCgp0YXJnZXRfc29jG
  AMgASgLMi0ucGNjcy5jaHJvbm9zLm1lc3NhZ2VzLnRhcmdldHNvYy52MS5UYXJnZXRTb2NCDuI/CxIJdGFyZ2V0U29jUgl0YXJnZ
  XRTb2MScgoScGVuZGluZ190YXJnZXRfc29jGAQgASgLMi0ucGNjcy5jaHJvbm9zLm1lc3NhZ2VzLnRhcmdldHNvYy52MS5UYXJnZ
  XRTb2NCFeI/EhIQcGVuZGluZ1RhcmdldFNvY1IQcGVuZGluZ1RhcmdldFNvYxIyCgp1cGRhdGVkX2F0GAUgASgDQg7iPwsSCXVwZ
  GF0ZWRBdEgAUgl1cGRhdGVkQXSIAQFCDQoLX3VwZGF0ZWRfYXQi+gIKE1NldFRhcmdldFNvY1JlcXVlc3QSVwoHcmVxdWVzdBgBI
  AEoCzIvLnBjY3MuY2hyb25vcy5tZXNzYWdlcy5jb21tb24udjEuQ2hyb25vc1JlcXVlc3RCDOI/CRIHcmVxdWVzdFIHcmVxdWVzd
  BJcChtiYXR0ZXJ5X2NoYXJnZV90YXJnZXRfbGV2ZWwYAiABKAVCHeI/GhIYYmF0dGVyeUNoYXJnZVRhcmdldExldmVsUhhiYXR0Z
  XJ5Q2hhcmdlVGFyZ2V0TGV2ZWwSqwEKIGNoYXJnZV90YXJnZXRfbGV2ZWxfc2V0dGluZ190eXBlGAMgASgOMkAucGNjcy5jaHJvb
  m9zLm1lc3NhZ2VzLnRhcmdldHNvYy52MS5DaGFyZ2VUYXJnZXRMZXZlbFNldHRpbmdUeXBlQiHiPx4SHGNoYXJnZVRhcmdldExld
  mVsU2V0dGluZ1R5cGVSHGNoYXJnZVRhcmdldExldmVsU2V0dGluZ1R5cGUiLwoUU2V0VGFyZ2V0U29jUmVzcG9uc2USFwoCaWQYA
  SABKAlCB+I/BBICaWRSAmlkKtIBChxDaGFyZ2VUYXJnZXRMZXZlbFNldHRpbmdUeXBlEmMKLENIQVJHRV9UQVJHRVRfTEVWRUxfU
  0VUVElOR19UWVBFX1VOU1BFQ0lGSUVEEAAaMeI/LhIsQ0hBUkdFX1RBUkdFVF9MRVZFTF9TRVRUSU5HX1RZUEVfVU5TUEVDSUZJR
  UQSFQoFREFJTFkQARoK4j8HEgVEQUlMWRIdCglMT05HX1RSSVAQAhoO4j8LEglMT05HX1RSSVASFwoGQ1VTVE9NEAMaC+I/CBIGQ
  1VTVE9NYgZwcm90bzM="""
        )
        .mkString
    )
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor =
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor
      .buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor =
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(
      javaProto,
      _root_.scala.Array(
        pccs.chronos.messages.common.v1.chronos_request.ChronosRequestProto.javaDescriptor
      )
    )
  @deprecated(
    "Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.",
    "ScalaPB 0.5.47"
  )
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
