site_name: Boat-Tracker
site_author: Michael Skogberg

theme:
  name: 'material'

nav:
  - Overview: index.md
  - Develop: develop.md
  - HTTP Endpoints: endpoints.md
  - Agent: agent.md
  - Support: support.md
  - Privacy: privacy.md

copyright: Copyright &copy; 2024 <a href="https://github.com/malliina">Michael Skogberg</a>
