// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package pccs.chronos.entities.common.v1.chronos_common

object ChronosCommonProto extends _root_.scalapb.GeneratedFileObject:
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq.empty
  lazy val messagesCompanions
    : Seq[_root_.scalapb.GeneratedMessageCompanion[? <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[? <: _root_.scalapb.GeneratedMessage]](
      pccs.chronos.entities.common.v1.chronos_common.TimeZone
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
    scalapb.Encoding.fromBase64(
      scala.collection.immutable
        .Seq(
          """ChRjaHJvbm9zX2NvbW1vbi5wcm90bxIfcGNjcy5jaHJvbm9zLmVudGl0aWVzLmNvbW1vbi52MSIjCghUaW1lWm9uZRIXCgJpZ
  BgBIAEoCUIH4j8EEgJpZFICaWRiBnByb3RvMw=="""
        )
        .mkString
    )
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor =
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor
      .buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor =
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(
      javaProto,
      _root_.scala.Array(
      )
    )
  @deprecated(
    "Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.",
    "ScalaPB 0.5.47"
  )
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
