### Reverse geocode
GET https://api.mapbox.com/search/geocode/v6/reverse?longitude=24.88260391&latitude=60.15126954&access_token={{access_token}}&limit=1

### Parking
GET https://api.hel.fi/servicemap/v2/administrative_division/?type=parking_area&page=1&page_size=500&geometry=true&unit_include=name%2Clocation%2Cstreet_address%2Caddress_zip%2Cmunicipality&extra__class=2&municipality=helsinki

### Capacity
GET https://pubapi.parkkiopas.fi/public/v1/parking_area/?format=json
