### Reverse geocode with Mapbox
GET https://api.mapbox.com/search/geocode/v6/reverse?longitude=24.88260391&latitude=60.15126954&access_token={{mapbox-token}}&limit=1

### Reverse geocode with Google
GET https://maps.googleapis.com/maps/api/geocode/json?latlng=60.15126954,24.88260391&key={{google-key}}&result_type=street_address

### Static image with Mapbox
GET https://api.mapbox.com/styles/v1/skogberglabs/{{mapbox-style}}/static/24.892,60.1527,14.25,0,60/400x400?access_token={{mapbox-token}}

### Parking
GET https://api.hel.fi/servicemap/v2/administrative_division/?type=parking_area&page=1&page_size=500&geometry=true&unit_include=name%2Clocation%2Cstreet_address%2Caddress_zip%2Cmunicipality&extra__class=2&municipality=helsinki

### Parking WFS
GET https://kartta.hel.fi/ws/geoserver/avoindata/wfs?request=getFeature&typeNames=avoindata:Pysakointipaikat_alue&outputFormat=application/json&srsName=EPSG:4326

### Capacity
GET https://pubapi.parkkiopas.fi/public/v1/parking_area/?format=json&page=13

### WFS
GET https://kartta.hel.fi/ws/geoserver/avoindata/wfs?request=getFeature&typename=avoindata:Pysakointipaikat_alue

### WFS JSON
GET https://kartta.hel.fi/ws/geoserver/avoindata/wfs?request=getFeature&typename=avoindata:Pysakointipaikat_alue&outputFormat=application/json

### WFS shape zip
GET https://kartta.hel.fi/ws/geoserver/avoindata/wfs?request=getFeature&typename=avoindata:Pysakointipaikat_alue&outputFormat=SHAPE-ZIP

### Nearby parkings
GET http://localhost:9000/cars/parkings/search?lng=24.9&lat=60.16

### Capacity
GET http://localhost:9000/cars/parkings/capacity
