// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package pccs.vehiclestates.entities.battery.v1.battery

@SerialVersionUID(0L)
final case class Battery(
  timestamp: _root_.scala.Option[pccs.vehiclestates.entities.common.v1.common.Timestamp] =
    _root_.scala.None,
  batteryChargeLevelPercentage: _root_.scala.Double = 0.0,
  averageEnergyConsumptionKwhPer100Km: _root_.scala.Double = 0.0,
  estimatedDistanceToEmptyKm: _root_.scala.Int = 0,
  estimatedChargingTimeToFullMinutes: _root_.scala.Int = 0,
  chargerConnectionStatus: pccs.vehiclestates.entities.battery.v1.battery.ChargerConnectionStatus =
    pccs.vehiclestates.entities.battery.v1.battery.ChargerConnectionStatus.CHARGER_CONNECTION_STATUS_UNSPECIFIED,
  chargingStatus: pccs.vehiclestates.entities.battery.v1.battery.ChargingStatus =
    pccs.vehiclestates.entities.battery.v1.battery.ChargingStatus.CHARGING_STATUS_UNSPECIFIED,
  estimatedDistanceToEmptyMiles: _root_.scala.Int = 0,
  estimatedChargingTimeMinutesToTargetDistance: _root_.scala.Int = 0,
  chargingPowerWatts: _root_.scala.Int = 0,
  chargingCurrentAmps: _root_.scala.Int = 0,
  averageEnergyConsumptionKwhPer100KmAutomatic: _root_.scala.Double = 0.0,
  averageEnergyConsumptionKwhPer100KmSinceCharge: _root_.scala.Double = 0.0,
  totalEnergyConsumptionWh: _root_.scala.Double = 0.0,
  totalEnergyConsumptionWhAutomatic: _root_.scala.Double = 0.0,
  totalEnergyConsumptionWhSinceCharge: _root_.scala.Double = 0.0,
  chargingType: pccs.vehiclestates.entities.battery.v1.battery.ChargingType =
    pccs.vehiclestates.entities.battery.v1.battery.ChargingType.CHARGING_TYPE_UNSPECIFIED,
  chargingVoltageVolts: _root_.scala.Int = 0,
  estimatedChargingTimeMinutesToMinimumSoc: _root_.scala.Int = 0,
  energyConsumptionWhManual: _root_.scala.Option[
    pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionWh
  ] = _root_.scala.None,
  energyConsumptionWhAutomatic: _root_.scala.Option[
    pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionWh
  ] = _root_.scala.None,
  energyConsumptionWhSinceCharge: _root_.scala.Option[
    pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionWh
  ] = _root_.scala.None,
  energyConsumptionPercentageManual: _root_.scala.Option[
    pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage
  ] = _root_.scala.None,
  energyConsumptionPercentageAutomatic: _root_.scala.Option[
    pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage
  ] = _root_.scala.None,
  energyConsumptionPercentageSinceCharge: _root_.scala.Option[
    pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage
  ] = _root_.scala.None,
  chargerPowerStatus: pccs.vehiclestates.entities.battery.v1.battery.ChargerPowerStatus =
    pccs.vehiclestates.entities.battery.v1.battery.ChargerPowerStatus.CHARGER_POWER_STATUS_UNSPECIFIED,
  unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
) extends scalapb.GeneratedMessage
  with scalapb.lenses.Updatable[Battery]:
  @transient
  private var __serializedSizeMemoized: _root_.scala.Int = 0
  private def __computeSerializedSize(): _root_.scala.Int =
    var __size = 0
    if timestamp.isDefined then
      val __value = timestamp.get
      __size += 1 + _root_.com.google.protobuf.CodedOutputStream
        .computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize;

    {
      val __value = batteryChargeLevelPercentage
      if __value != 0.0 then
        __size += _root_.com.google.protobuf.CodedOutputStream.computeDoubleSize(2, __value)
    };

    {
      val __value = averageEnergyConsumptionKwhPer100Km
      if __value != 0.0 then
        __size += _root_.com.google.protobuf.CodedOutputStream.computeDoubleSize(3, __value)
    };

    {
      val __value = estimatedDistanceToEmptyKm
      if __value != 0 then
        __size += _root_.com.google.protobuf.CodedOutputStream.computeInt32Size(4, __value)
    };

    {
      val __value = estimatedChargingTimeToFullMinutes
      if __value != 0 then
        __size += _root_.com.google.protobuf.CodedOutputStream.computeInt32Size(5, __value)
    };

    {
      val __value = chargerConnectionStatus.value
      if __value != 0 then
        __size += _root_.com.google.protobuf.CodedOutputStream.computeEnumSize(6, __value)
    };

    {
      val __value = chargingStatus.value
      if __value != 0 then
        __size += _root_.com.google.protobuf.CodedOutputStream.computeEnumSize(7, __value)
    };

    {
      val __value = estimatedDistanceToEmptyMiles
      if __value != 0 then
        __size += _root_.com.google.protobuf.CodedOutputStream.computeInt32Size(8, __value)
    };

    {
      val __value = estimatedChargingTimeMinutesToTargetDistance
      if __value != 0 then
        __size += _root_.com.google.protobuf.CodedOutputStream.computeInt32Size(9, __value)
    };

    {
      val __value = chargingPowerWatts
      if __value != 0 then
        __size += _root_.com.google.protobuf.CodedOutputStream.computeInt32Size(10, __value)
    };

    {
      val __value = chargingCurrentAmps
      if __value != 0 then
        __size += _root_.com.google.protobuf.CodedOutputStream.computeInt32Size(11, __value)
    };

    {
      val __value = averageEnergyConsumptionKwhPer100KmAutomatic
      if __value != 0.0 then
        __size += _root_.com.google.protobuf.CodedOutputStream.computeDoubleSize(12, __value)
    };

    {
      val __value = averageEnergyConsumptionKwhPer100KmSinceCharge
      if __value != 0.0 then
        __size += _root_.com.google.protobuf.CodedOutputStream.computeDoubleSize(13, __value)
    };

    {
      val __value = totalEnergyConsumptionWh
      if __value != 0.0 then
        __size += _root_.com.google.protobuf.CodedOutputStream.computeDoubleSize(14, __value)
    };

    {
      val __value = totalEnergyConsumptionWhAutomatic
      if __value != 0.0 then
        __size += _root_.com.google.protobuf.CodedOutputStream.computeDoubleSize(15, __value)
    };

    {
      val __value = totalEnergyConsumptionWhSinceCharge
      if __value != 0.0 then
        __size += _root_.com.google.protobuf.CodedOutputStream.computeDoubleSize(16, __value)
    };

    {
      val __value = chargingType.value
      if __value != 0 then
        __size += _root_.com.google.protobuf.CodedOutputStream.computeEnumSize(17, __value)
    };

    {
      val __value = chargingVoltageVolts
      if __value != 0 then
        __size += _root_.com.google.protobuf.CodedOutputStream.computeInt32Size(18, __value)
    };

    {
      val __value = estimatedChargingTimeMinutesToMinimumSoc
      if __value != 0 then
        __size += _root_.com.google.protobuf.CodedOutputStream.computeInt32Size(19, __value)
    };
    if energyConsumptionWhManual.isDefined then
      val __value = energyConsumptionWhManual.get
      __size += 2 + _root_.com.google.protobuf.CodedOutputStream
        .computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize;
    if energyConsumptionWhAutomatic.isDefined then
      val __value = energyConsumptionWhAutomatic.get
      __size += 2 + _root_.com.google.protobuf.CodedOutputStream
        .computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize;
    if energyConsumptionWhSinceCharge.isDefined then
      val __value = energyConsumptionWhSinceCharge.get
      __size += 2 + _root_.com.google.protobuf.CodedOutputStream
        .computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize;
    if energyConsumptionPercentageManual.isDefined then
      val __value = energyConsumptionPercentageManual.get
      __size += 2 + _root_.com.google.protobuf.CodedOutputStream
        .computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize;
    if energyConsumptionPercentageAutomatic.isDefined then
      val __value = energyConsumptionPercentageAutomatic.get
      __size += 2 + _root_.com.google.protobuf.CodedOutputStream
        .computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize;
    if energyConsumptionPercentageSinceCharge.isDefined then
      val __value = energyConsumptionPercentageSinceCharge.get
      __size += 2 + _root_.com.google.protobuf.CodedOutputStream
        .computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize;

    {
      val __value = chargerPowerStatus.value
      if __value != 0 then
        __size += _root_.com.google.protobuf.CodedOutputStream.computeEnumSize(26, __value)
    };
    __size += unknownFields.serializedSize
    __size
  override def serializedSize: _root_.scala.Int =
    var __size = __serializedSizeMemoized
    if __size == 0 then
      __size = __computeSerializedSize() + 1
      __serializedSizeMemoized = __size
    __size - 1

  def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit =
    timestamp.foreach: __v =>
      val __m = __v
      _output__.writeTag(1, 2)
      _output__.writeUInt32NoTag(__m.serializedSize)
      __m.writeTo(_output__)
    ;
    {
      val __v = batteryChargeLevelPercentage
      if __v != 0.0 then _output__.writeDouble(2, __v)
    };
    {
      val __v = averageEnergyConsumptionKwhPer100Km
      if __v != 0.0 then _output__.writeDouble(3, __v)
    };
    {
      val __v = estimatedDistanceToEmptyKm
      if __v != 0 then _output__.writeInt32(4, __v)
    };
    {
      val __v = estimatedChargingTimeToFullMinutes
      if __v != 0 then _output__.writeInt32(5, __v)
    };
    {
      val __v = chargerConnectionStatus.value
      if __v != 0 then _output__.writeEnum(6, __v)
    };
    {
      val __v = chargingStatus.value
      if __v != 0 then _output__.writeEnum(7, __v)
    };
    {
      val __v = estimatedDistanceToEmptyMiles
      if __v != 0 then _output__.writeInt32(8, __v)
    };
    {
      val __v = estimatedChargingTimeMinutesToTargetDistance
      if __v != 0 then _output__.writeInt32(9, __v)
    };
    {
      val __v = chargingPowerWatts
      if __v != 0 then _output__.writeInt32(10, __v)
    };
    {
      val __v = chargingCurrentAmps
      if __v != 0 then _output__.writeInt32(11, __v)
    };
    {
      val __v = averageEnergyConsumptionKwhPer100KmAutomatic
      if __v != 0.0 then _output__.writeDouble(12, __v)
    };
    {
      val __v = averageEnergyConsumptionKwhPer100KmSinceCharge
      if __v != 0.0 then _output__.writeDouble(13, __v)
    };
    {
      val __v = totalEnergyConsumptionWh
      if __v != 0.0 then _output__.writeDouble(14, __v)
    };
    {
      val __v = totalEnergyConsumptionWhAutomatic
      if __v != 0.0 then _output__.writeDouble(15, __v)
    };
    {
      val __v = totalEnergyConsumptionWhSinceCharge
      if __v != 0.0 then _output__.writeDouble(16, __v)
    };
    {
      val __v = chargingType.value
      if __v != 0 then _output__.writeEnum(17, __v)
    };
    {
      val __v = chargingVoltageVolts
      if __v != 0 then _output__.writeInt32(18, __v)
    };
    {
      val __v = estimatedChargingTimeMinutesToMinimumSoc
      if __v != 0 then _output__.writeInt32(19, __v)
    };
    energyConsumptionWhManual.foreach: __v =>
      val __m = __v
      _output__.writeTag(20, 2)
      _output__.writeUInt32NoTag(__m.serializedSize)
      __m.writeTo(_output__)
    ;
    energyConsumptionWhAutomatic.foreach: __v =>
      val __m = __v
      _output__.writeTag(21, 2)
      _output__.writeUInt32NoTag(__m.serializedSize)
      __m.writeTo(_output__)
    ;
    energyConsumptionWhSinceCharge.foreach: __v =>
      val __m = __v
      _output__.writeTag(22, 2)
      _output__.writeUInt32NoTag(__m.serializedSize)
      __m.writeTo(_output__)
    ;
    energyConsumptionPercentageManual.foreach: __v =>
      val __m = __v
      _output__.writeTag(23, 2)
      _output__.writeUInt32NoTag(__m.serializedSize)
      __m.writeTo(_output__)
    ;
    energyConsumptionPercentageAutomatic.foreach: __v =>
      val __m = __v
      _output__.writeTag(24, 2)
      _output__.writeUInt32NoTag(__m.serializedSize)
      __m.writeTo(_output__)
    ;
    energyConsumptionPercentageSinceCharge.foreach: __v =>
      val __m = __v
      _output__.writeTag(25, 2)
      _output__.writeUInt32NoTag(__m.serializedSize)
      __m.writeTo(_output__)
    ;
    {
      val __v = chargerPowerStatus.value
      if __v != 0 then _output__.writeEnum(26, __v)
    };
    unknownFields.writeTo(_output__)
  def getTimestamp: pccs.vehiclestates.entities.common.v1.common.Timestamp =
    timestamp.getOrElse(pccs.vehiclestates.entities.common.v1.common.Timestamp.defaultInstance)
  def clearTimestamp: Battery = copy(timestamp = _root_.scala.None)
  def withTimestamp(__v: pccs.vehiclestates.entities.common.v1.common.Timestamp): Battery =
    copy(timestamp = Option(__v))
  def withBatteryChargeLevelPercentage(__v: _root_.scala.Double): Battery =
    copy(batteryChargeLevelPercentage = __v)
  def withAverageEnergyConsumptionKwhPer100Km(__v: _root_.scala.Double): Battery =
    copy(averageEnergyConsumptionKwhPer100Km = __v)
  def withEstimatedDistanceToEmptyKm(__v: _root_.scala.Int): Battery =
    copy(estimatedDistanceToEmptyKm = __v)
  def withEstimatedChargingTimeToFullMinutes(__v: _root_.scala.Int): Battery =
    copy(estimatedChargingTimeToFullMinutes = __v)
  def withChargerConnectionStatus(
    __v: pccs.vehiclestates.entities.battery.v1.battery.ChargerConnectionStatus
  ): Battery = copy(chargerConnectionStatus = __v)
  def withChargingStatus(
    __v: pccs.vehiclestates.entities.battery.v1.battery.ChargingStatus
  ): Battery = copy(chargingStatus = __v)
  def withEstimatedDistanceToEmptyMiles(__v: _root_.scala.Int): Battery =
    copy(estimatedDistanceToEmptyMiles = __v)
  def withEstimatedChargingTimeMinutesToTargetDistance(__v: _root_.scala.Int): Battery =
    copy(estimatedChargingTimeMinutesToTargetDistance = __v)
  def withChargingPowerWatts(__v: _root_.scala.Int): Battery = copy(chargingPowerWatts = __v)
  def withChargingCurrentAmps(__v: _root_.scala.Int): Battery = copy(chargingCurrentAmps = __v)
  def withAverageEnergyConsumptionKwhPer100KmAutomatic(__v: _root_.scala.Double): Battery =
    copy(averageEnergyConsumptionKwhPer100KmAutomatic = __v)
  def withAverageEnergyConsumptionKwhPer100KmSinceCharge(__v: _root_.scala.Double): Battery =
    copy(averageEnergyConsumptionKwhPer100KmSinceCharge = __v)
  def withTotalEnergyConsumptionWh(__v: _root_.scala.Double): Battery =
    copy(totalEnergyConsumptionWh = __v)
  def withTotalEnergyConsumptionWhAutomatic(__v: _root_.scala.Double): Battery =
    copy(totalEnergyConsumptionWhAutomatic = __v)
  def withTotalEnergyConsumptionWhSinceCharge(__v: _root_.scala.Double): Battery =
    copy(totalEnergyConsumptionWhSinceCharge = __v)
  def withChargingType(__v: pccs.vehiclestates.entities.battery.v1.battery.ChargingType): Battery =
    copy(chargingType = __v)
  def withChargingVoltageVolts(__v: _root_.scala.Int): Battery = copy(chargingVoltageVolts = __v)
  def withEstimatedChargingTimeMinutesToMinimumSoc(__v: _root_.scala.Int): Battery =
    copy(estimatedChargingTimeMinutesToMinimumSoc = __v)
  def getEnergyConsumptionWhManual
    : pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionWh =
    energyConsumptionWhManual.getOrElse(
      pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionWh.defaultInstance
    )
  def clearEnergyConsumptionWhManual: Battery = copy(energyConsumptionWhManual = _root_.scala.None)
  def withEnergyConsumptionWhManual(
    __v: pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionWh
  ): Battery = copy(energyConsumptionWhManual = Option(__v))
  def getEnergyConsumptionWhAutomatic
    : pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionWh =
    energyConsumptionWhAutomatic.getOrElse(
      pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionWh.defaultInstance
    )
  def clearEnergyConsumptionWhAutomatic: Battery =
    copy(energyConsumptionWhAutomatic = _root_.scala.None)
  def withEnergyConsumptionWhAutomatic(
    __v: pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionWh
  ): Battery = copy(energyConsumptionWhAutomatic = Option(__v))
  def getEnergyConsumptionWhSinceCharge
    : pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionWh =
    energyConsumptionWhSinceCharge.getOrElse(
      pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionWh.defaultInstance
    )
  def clearEnergyConsumptionWhSinceCharge: Battery =
    copy(energyConsumptionWhSinceCharge = _root_.scala.None)
  def withEnergyConsumptionWhSinceCharge(
    __v: pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionWh
  ): Battery = copy(energyConsumptionWhSinceCharge = Option(__v))
  def getEnergyConsumptionPercentageManual
    : pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage =
    energyConsumptionPercentageManual.getOrElse(
      pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage.defaultInstance
    )
  def clearEnergyConsumptionPercentageManual: Battery =
    copy(energyConsumptionPercentageManual = _root_.scala.None)
  def withEnergyConsumptionPercentageManual(
    __v: pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage
  ): Battery = copy(energyConsumptionPercentageManual = Option(__v))
  def getEnergyConsumptionPercentageAutomatic
    : pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage =
    energyConsumptionPercentageAutomatic.getOrElse(
      pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage.defaultInstance
    )
  def clearEnergyConsumptionPercentageAutomatic: Battery =
    copy(energyConsumptionPercentageAutomatic = _root_.scala.None)
  def withEnergyConsumptionPercentageAutomatic(
    __v: pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage
  ): Battery = copy(energyConsumptionPercentageAutomatic = Option(__v))
  def getEnergyConsumptionPercentageSinceCharge
    : pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage =
    energyConsumptionPercentageSinceCharge.getOrElse(
      pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage.defaultInstance
    )
  def clearEnergyConsumptionPercentageSinceCharge: Battery =
    copy(energyConsumptionPercentageSinceCharge = _root_.scala.None)
  def withEnergyConsumptionPercentageSinceCharge(
    __v: pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage
  ): Battery = copy(energyConsumptionPercentageSinceCharge = Option(__v))
  def withChargerPowerStatus(
    __v: pccs.vehiclestates.entities.battery.v1.battery.ChargerPowerStatus
  ): Battery = copy(chargerPowerStatus = __v)
  def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
  def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
  def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any =
    (__fieldNumber: @ _root_.scala.unchecked) match
      case 1 => timestamp.orNull
      case 2 =>
        val __t = batteryChargeLevelPercentage
        if __t != 0.0 then __t else null
      case 3 =>
        val __t = averageEnergyConsumptionKwhPer100Km
        if __t != 0.0 then __t else null
      case 4 =>
        val __t = estimatedDistanceToEmptyKm
        if __t != 0 then __t else null
      case 5 =>
        val __t = estimatedChargingTimeToFullMinutes
        if __t != 0 then __t else null
      case 6 =>
        val __t = chargerConnectionStatus.javaValueDescriptor
        if __t.getNumber() != 0 then __t else null
      case 7 =>
        val __t = chargingStatus.javaValueDescriptor
        if __t.getNumber() != 0 then __t else null
      case 8 =>
        val __t = estimatedDistanceToEmptyMiles
        if __t != 0 then __t else null
      case 9 =>
        val __t = estimatedChargingTimeMinutesToTargetDistance
        if __t != 0 then __t else null
      case 10 =>
        val __t = chargingPowerWatts
        if __t != 0 then __t else null
      case 11 =>
        val __t = chargingCurrentAmps
        if __t != 0 then __t else null
      case 12 =>
        val __t = averageEnergyConsumptionKwhPer100KmAutomatic
        if __t != 0.0 then __t else null
      case 13 =>
        val __t = averageEnergyConsumptionKwhPer100KmSinceCharge
        if __t != 0.0 then __t else null
      case 14 =>
        val __t = totalEnergyConsumptionWh
        if __t != 0.0 then __t else null
      case 15 =>
        val __t = totalEnergyConsumptionWhAutomatic
        if __t != 0.0 then __t else null
      case 16 =>
        val __t = totalEnergyConsumptionWhSinceCharge
        if __t != 0.0 then __t else null
      case 17 =>
        val __t = chargingType.javaValueDescriptor
        if __t.getNumber() != 0 then __t else null
      case 18 =>
        val __t = chargingVoltageVolts
        if __t != 0 then __t else null
      case 19 =>
        val __t = estimatedChargingTimeMinutesToMinimumSoc
        if __t != 0 then __t else null
      case 20 => energyConsumptionWhManual.orNull
      case 21 => energyConsumptionWhAutomatic.orNull
      case 22 => energyConsumptionWhSinceCharge.orNull
      case 23 => energyConsumptionPercentageManual.orNull
      case 24 => energyConsumptionPercentageAutomatic.orNull
      case 25 => energyConsumptionPercentageSinceCharge.orNull
      case 26 =>
        val __t = chargerPowerStatus.javaValueDescriptor
        if __t.getNumber() != 0 then __t else null
  def getField(
    __field: _root_.scalapb.descriptors.FieldDescriptor
  ): _root_.scalapb.descriptors.PValue =
    _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
    (__field.number: @ _root_.scala.unchecked) match
      case 1  => timestamp.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
      case 2  => _root_.scalapb.descriptors.PDouble(batteryChargeLevelPercentage)
      case 3  => _root_.scalapb.descriptors.PDouble(averageEnergyConsumptionKwhPer100Km)
      case 4  => _root_.scalapb.descriptors.PInt(estimatedDistanceToEmptyKm)
      case 5  => _root_.scalapb.descriptors.PInt(estimatedChargingTimeToFullMinutes)
      case 6  => _root_.scalapb.descriptors.PEnum(chargerConnectionStatus.scalaValueDescriptor)
      case 7  => _root_.scalapb.descriptors.PEnum(chargingStatus.scalaValueDescriptor)
      case 8  => _root_.scalapb.descriptors.PInt(estimatedDistanceToEmptyMiles)
      case 9  => _root_.scalapb.descriptors.PInt(estimatedChargingTimeMinutesToTargetDistance)
      case 10 => _root_.scalapb.descriptors.PInt(chargingPowerWatts)
      case 11 => _root_.scalapb.descriptors.PInt(chargingCurrentAmps)
      case 12 => _root_.scalapb.descriptors.PDouble(averageEnergyConsumptionKwhPer100KmAutomatic)
      case 13 => _root_.scalapb.descriptors.PDouble(averageEnergyConsumptionKwhPer100KmSinceCharge)
      case 14 => _root_.scalapb.descriptors.PDouble(totalEnergyConsumptionWh)
      case 15 => _root_.scalapb.descriptors.PDouble(totalEnergyConsumptionWhAutomatic)
      case 16 => _root_.scalapb.descriptors.PDouble(totalEnergyConsumptionWhSinceCharge)
      case 17 => _root_.scalapb.descriptors.PEnum(chargingType.scalaValueDescriptor)
      case 18 => _root_.scalapb.descriptors.PInt(chargingVoltageVolts)
      case 19 => _root_.scalapb.descriptors.PInt(estimatedChargingTimeMinutesToMinimumSoc)
      case 20 =>
        energyConsumptionWhManual.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
      case 21 =>
        energyConsumptionWhAutomatic.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
      case 22 =>
        energyConsumptionWhSinceCharge
          .map(_.toPMessage)
          .getOrElse(_root_.scalapb.descriptors.PEmpty)
      case 23 =>
        energyConsumptionPercentageManual
          .map(_.toPMessage)
          .getOrElse(_root_.scalapb.descriptors.PEmpty)
      case 24 =>
        energyConsumptionPercentageAutomatic
          .map(_.toPMessage)
          .getOrElse(_root_.scalapb.descriptors.PEmpty)
      case 25 =>
        energyConsumptionPercentageSinceCharge
          .map(_.toPMessage)
          .getOrElse(_root_.scalapb.descriptors.PEmpty)
      case 26 => _root_.scalapb.descriptors.PEnum(chargerPowerStatus.scalaValueDescriptor)
  def toProtoString: _root_.scala.Predef.String =
    _root_.scalapb.TextFormat.printToUnicodeString(this)
  def companion: pccs.vehiclestates.entities.battery.v1.battery.Battery.type =
    pccs.vehiclestates.entities.battery.v1.battery.Battery
  // @@protoc_insertion_point(GeneratedMessage[pccs.vehiclestates.entities.battery.v1.Battery])

object Battery
  extends scalapb.GeneratedMessageCompanion[pccs.vehiclestates.entities.battery.v1.battery.Battery]:
  implicit def messageCompanion
    : scalapb.GeneratedMessageCompanion[pccs.vehiclestates.entities.battery.v1.battery.Battery] =
    this
  def parseFrom(
    `_input__`: _root_.com.google.protobuf.CodedInputStream
  ): pccs.vehiclestates.entities.battery.v1.battery.Battery =
    var __timestamp: _root_.scala.Option[pccs.vehiclestates.entities.common.v1.common.Timestamp] =
      _root_.scala.None
    var __batteryChargeLevelPercentage: _root_.scala.Double = 0.0
    var __averageEnergyConsumptionKwhPer100Km: _root_.scala.Double = 0.0
    var __estimatedDistanceToEmptyKm: _root_.scala.Int = 0
    var __estimatedChargingTimeToFullMinutes: _root_.scala.Int = 0
    var __chargerConnectionStatus
      : pccs.vehiclestates.entities.battery.v1.battery.ChargerConnectionStatus =
      pccs.vehiclestates.entities.battery.v1.battery.ChargerConnectionStatus.CHARGER_CONNECTION_STATUS_UNSPECIFIED
    var __chargingStatus: pccs.vehiclestates.entities.battery.v1.battery.ChargingStatus =
      pccs.vehiclestates.entities.battery.v1.battery.ChargingStatus.CHARGING_STATUS_UNSPECIFIED
    var __estimatedDistanceToEmptyMiles: _root_.scala.Int = 0
    var __estimatedChargingTimeMinutesToTargetDistance: _root_.scala.Int = 0
    var __chargingPowerWatts: _root_.scala.Int = 0
    var __chargingCurrentAmps: _root_.scala.Int = 0
    var __averageEnergyConsumptionKwhPer100KmAutomatic: _root_.scala.Double = 0.0
    var __averageEnergyConsumptionKwhPer100KmSinceCharge: _root_.scala.Double = 0.0
    var __totalEnergyConsumptionWh: _root_.scala.Double = 0.0
    var __totalEnergyConsumptionWhAutomatic: _root_.scala.Double = 0.0
    var __totalEnergyConsumptionWhSinceCharge: _root_.scala.Double = 0.0
    var __chargingType: pccs.vehiclestates.entities.battery.v1.battery.ChargingType =
      pccs.vehiclestates.entities.battery.v1.battery.ChargingType.CHARGING_TYPE_UNSPECIFIED
    var __chargingVoltageVolts: _root_.scala.Int = 0
    var __estimatedChargingTimeMinutesToMinimumSoc: _root_.scala.Int = 0
    var __energyConsumptionWhManual
      : _root_.scala.Option[pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionWh] =
      _root_.scala.None
    var __energyConsumptionWhAutomatic
      : _root_.scala.Option[pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionWh] =
      _root_.scala.None
    var __energyConsumptionWhSinceCharge
      : _root_.scala.Option[pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionWh] =
      _root_.scala.None
    var __energyConsumptionPercentageManual: _root_.scala.Option[
      pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage
    ] = _root_.scala.None
    var __energyConsumptionPercentageAutomatic: _root_.scala.Option[
      pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage
    ] = _root_.scala.None
    var __energyConsumptionPercentageSinceCharge: _root_.scala.Option[
      pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage
    ] = _root_.scala.None
    var __chargerPowerStatus: pccs.vehiclestates.entities.battery.v1.battery.ChargerPowerStatus =
      pccs.vehiclestates.entities.battery.v1.battery.ChargerPowerStatus.CHARGER_POWER_STATUS_UNSPECIFIED
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while !_done__ do
      val _tag__ = _input__.readTag()
      _tag__ match
        case 0  => _done__ = true
        case 10 =>
          __timestamp = _root_.scala.Option(
            __timestamp.fold(
              _root_.scalapb.LiteParser
                .readMessage[pccs.vehiclestates.entities.common.v1.common.Timestamp](_input__)
            )(_root_.scalapb.LiteParser.readMessage(_input__, _))
          )
        case 17 =>
          __batteryChargeLevelPercentage = _input__.readDouble()
        case 25 =>
          __averageEnergyConsumptionKwhPer100Km = _input__.readDouble()
        case 32 =>
          __estimatedDistanceToEmptyKm = _input__.readInt32()
        case 40 =>
          __estimatedChargingTimeToFullMinutes = _input__.readInt32()
        case 48 =>
          __chargerConnectionStatus =
            pccs.vehiclestates.entities.battery.v1.battery.ChargerConnectionStatus
              .fromValue(_input__.readEnum())
        case 56 =>
          __chargingStatus = pccs.vehiclestates.entities.battery.v1.battery.ChargingStatus
            .fromValue(_input__.readEnum())
        case 64 =>
          __estimatedDistanceToEmptyMiles = _input__.readInt32()
        case 72 =>
          __estimatedChargingTimeMinutesToTargetDistance = _input__.readInt32()
        case 80 =>
          __chargingPowerWatts = _input__.readInt32()
        case 88 =>
          __chargingCurrentAmps = _input__.readInt32()
        case 97 =>
          __averageEnergyConsumptionKwhPer100KmAutomatic = _input__.readDouble()
        case 105 =>
          __averageEnergyConsumptionKwhPer100KmSinceCharge = _input__.readDouble()
        case 113 =>
          __totalEnergyConsumptionWh = _input__.readDouble()
        case 121 =>
          __totalEnergyConsumptionWhAutomatic = _input__.readDouble()
        case 129 =>
          __totalEnergyConsumptionWhSinceCharge = _input__.readDouble()
        case 136 =>
          __chargingType = pccs.vehiclestates.entities.battery.v1.battery.ChargingType
            .fromValue(_input__.readEnum())
        case 144 =>
          __chargingVoltageVolts = _input__.readInt32()
        case 152 =>
          __estimatedChargingTimeMinutesToMinimumSoc = _input__.readInt32()
        case 162 =>
          __energyConsumptionWhManual = _root_.scala.Option(
            __energyConsumptionWhManual.fold(
              _root_.scalapb.LiteParser
                .readMessage[pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionWh](
                  _input__
                )
            )(_root_.scalapb.LiteParser.readMessage(_input__, _))
          )
        case 170 =>
          __energyConsumptionWhAutomatic = _root_.scala.Option(
            __energyConsumptionWhAutomatic.fold(
              _root_.scalapb.LiteParser
                .readMessage[pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionWh](
                  _input__
                )
            )(_root_.scalapb.LiteParser.readMessage(_input__, _))
          )
        case 178 =>
          __energyConsumptionWhSinceCharge = _root_.scala.Option(
            __energyConsumptionWhSinceCharge.fold(
              _root_.scalapb.LiteParser
                .readMessage[pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionWh](
                  _input__
                )
            )(_root_.scalapb.LiteParser.readMessage(_input__, _))
          )
        case 186 =>
          __energyConsumptionPercentageManual = _root_.scala.Option(
            __energyConsumptionPercentageManual.fold(
              _root_.scalapb.LiteParser.readMessage[
                pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage
              ](_input__)
            )(_root_.scalapb.LiteParser.readMessage(_input__, _))
          )
        case 194 =>
          __energyConsumptionPercentageAutomatic = _root_.scala.Option(
            __energyConsumptionPercentageAutomatic.fold(
              _root_.scalapb.LiteParser.readMessage[
                pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage
              ](_input__)
            )(_root_.scalapb.LiteParser.readMessage(_input__, _))
          )
        case 202 =>
          __energyConsumptionPercentageSinceCharge = _root_.scala.Option(
            __energyConsumptionPercentageSinceCharge.fold(
              _root_.scalapb.LiteParser.readMessage[
                pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage
              ](_input__)
            )(_root_.scalapb.LiteParser.readMessage(_input__, _))
          )
        case 208 =>
          __chargerPowerStatus = pccs.vehiclestates.entities.battery.v1.battery.ChargerPowerStatus
            .fromValue(_input__.readEnum())
        case tag =>
          if _unknownFields__ == null then
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          _unknownFields__.parseField(tag, _input__)
    pccs.vehiclestates.entities.battery.v1.battery.Battery(
      timestamp = __timestamp,
      batteryChargeLevelPercentage = __batteryChargeLevelPercentage,
      averageEnergyConsumptionKwhPer100Km = __averageEnergyConsumptionKwhPer100Km,
      estimatedDistanceToEmptyKm = __estimatedDistanceToEmptyKm,
      estimatedChargingTimeToFullMinutes = __estimatedChargingTimeToFullMinutes,
      chargerConnectionStatus = __chargerConnectionStatus,
      chargingStatus = __chargingStatus,
      estimatedDistanceToEmptyMiles = __estimatedDistanceToEmptyMiles,
      estimatedChargingTimeMinutesToTargetDistance = __estimatedChargingTimeMinutesToTargetDistance,
      chargingPowerWatts = __chargingPowerWatts,
      chargingCurrentAmps = __chargingCurrentAmps,
      averageEnergyConsumptionKwhPer100KmAutomatic = __averageEnergyConsumptionKwhPer100KmAutomatic,
      averageEnergyConsumptionKwhPer100KmSinceCharge =
        __averageEnergyConsumptionKwhPer100KmSinceCharge,
      totalEnergyConsumptionWh = __totalEnergyConsumptionWh,
      totalEnergyConsumptionWhAutomatic = __totalEnergyConsumptionWhAutomatic,
      totalEnergyConsumptionWhSinceCharge = __totalEnergyConsumptionWhSinceCharge,
      chargingType = __chargingType,
      chargingVoltageVolts = __chargingVoltageVolts,
      estimatedChargingTimeMinutesToMinimumSoc = __estimatedChargingTimeMinutesToMinimumSoc,
      energyConsumptionWhManual = __energyConsumptionWhManual,
      energyConsumptionWhAutomatic = __energyConsumptionWhAutomatic,
      energyConsumptionWhSinceCharge = __energyConsumptionWhSinceCharge,
      energyConsumptionPercentageManual = __energyConsumptionPercentageManual,
      energyConsumptionPercentageAutomatic = __energyConsumptionPercentageAutomatic,
      energyConsumptionPercentageSinceCharge = __energyConsumptionPercentageSinceCharge,
      chargerPowerStatus = __chargerPowerStatus,
      unknownFields = if _unknownFields__ == null then _root_.scalapb.UnknownFieldSet.empty
      else _unknownFields__.result()
    )
  implicit def messageReads
    : _root_.scalapb.descriptors.Reads[pccs.vehiclestates.entities.battery.v1.battery.Battery] =
    _root_.scalapb.descriptors.Reads {
      case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
        _root_.scala.Predef.require(
          __fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor),
          "FieldDescriptor does not match message type."
        )
        pccs.vehiclestates.entities.battery.v1.battery.Battery(
          timestamp = __fieldsMap
            .get(scalaDescriptor.findFieldByNumber(1).get)
            .flatMap(
              _.as[_root_.scala.Option[pccs.vehiclestates.entities.common.v1.common.Timestamp]]
            ),
          batteryChargeLevelPercentage = __fieldsMap
            .get(scalaDescriptor.findFieldByNumber(2).get)
            .map(_.as[_root_.scala.Double])
            .getOrElse(0.0),
          averageEnergyConsumptionKwhPer100Km = __fieldsMap
            .get(scalaDescriptor.findFieldByNumber(3).get)
            .map(_.as[_root_.scala.Double])
            .getOrElse(0.0),
          estimatedDistanceToEmptyKm = __fieldsMap
            .get(scalaDescriptor.findFieldByNumber(4).get)
            .map(_.as[_root_.scala.Int])
            .getOrElse(0),
          estimatedChargingTimeToFullMinutes = __fieldsMap
            .get(scalaDescriptor.findFieldByNumber(5).get)
            .map(_.as[_root_.scala.Int])
            .getOrElse(0),
          chargerConnectionStatus =
            pccs.vehiclestates.entities.battery.v1.battery.ChargerConnectionStatus.fromValue(
              __fieldsMap
                .get(scalaDescriptor.findFieldByNumber(6).get)
                .map(_.as[_root_.scalapb.descriptors.EnumValueDescriptor])
                .getOrElse(
                  pccs.vehiclestates.entities.battery.v1.battery.ChargerConnectionStatus.CHARGER_CONNECTION_STATUS_UNSPECIFIED.scalaValueDescriptor
                )
                .number
            ),
          chargingStatus = pccs.vehiclestates.entities.battery.v1.battery.ChargingStatus.fromValue(
            __fieldsMap
              .get(scalaDescriptor.findFieldByNumber(7).get)
              .map(_.as[_root_.scalapb.descriptors.EnumValueDescriptor])
              .getOrElse(
                pccs.vehiclestates.entities.battery.v1.battery.ChargingStatus.CHARGING_STATUS_UNSPECIFIED.scalaValueDescriptor
              )
              .number
          ),
          estimatedDistanceToEmptyMiles = __fieldsMap
            .get(scalaDescriptor.findFieldByNumber(8).get)
            .map(_.as[_root_.scala.Int])
            .getOrElse(0),
          estimatedChargingTimeMinutesToTargetDistance = __fieldsMap
            .get(scalaDescriptor.findFieldByNumber(9).get)
            .map(_.as[_root_.scala.Int])
            .getOrElse(0),
          chargingPowerWatts = __fieldsMap
            .get(scalaDescriptor.findFieldByNumber(10).get)
            .map(_.as[_root_.scala.Int])
            .getOrElse(0),
          chargingCurrentAmps = __fieldsMap
            .get(scalaDescriptor.findFieldByNumber(11).get)
            .map(_.as[_root_.scala.Int])
            .getOrElse(0),
          averageEnergyConsumptionKwhPer100KmAutomatic = __fieldsMap
            .get(scalaDescriptor.findFieldByNumber(12).get)
            .map(_.as[_root_.scala.Double])
            .getOrElse(0.0),
          averageEnergyConsumptionKwhPer100KmSinceCharge = __fieldsMap
            .get(scalaDescriptor.findFieldByNumber(13).get)
            .map(_.as[_root_.scala.Double])
            .getOrElse(0.0),
          totalEnergyConsumptionWh = __fieldsMap
            .get(scalaDescriptor.findFieldByNumber(14).get)
            .map(_.as[_root_.scala.Double])
            .getOrElse(0.0),
          totalEnergyConsumptionWhAutomatic = __fieldsMap
            .get(scalaDescriptor.findFieldByNumber(15).get)
            .map(_.as[_root_.scala.Double])
            .getOrElse(0.0),
          totalEnergyConsumptionWhSinceCharge = __fieldsMap
            .get(scalaDescriptor.findFieldByNumber(16).get)
            .map(_.as[_root_.scala.Double])
            .getOrElse(0.0),
          chargingType = pccs.vehiclestates.entities.battery.v1.battery.ChargingType.fromValue(
            __fieldsMap
              .get(scalaDescriptor.findFieldByNumber(17).get)
              .map(_.as[_root_.scalapb.descriptors.EnumValueDescriptor])
              .getOrElse(
                pccs.vehiclestates.entities.battery.v1.battery.ChargingType.CHARGING_TYPE_UNSPECIFIED.scalaValueDescriptor
              )
              .number
          ),
          chargingVoltageVolts = __fieldsMap
            .get(scalaDescriptor.findFieldByNumber(18).get)
            .map(_.as[_root_.scala.Int])
            .getOrElse(0),
          estimatedChargingTimeMinutesToMinimumSoc = __fieldsMap
            .get(scalaDescriptor.findFieldByNumber(19).get)
            .map(_.as[_root_.scala.Int])
            .getOrElse(0),
          energyConsumptionWhManual = __fieldsMap
            .get(scalaDescriptor.findFieldByNumber(20).get)
            .flatMap(
              _.as[_root_.scala.Option[
                pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionWh
              ]]
            ),
          energyConsumptionWhAutomatic = __fieldsMap
            .get(scalaDescriptor.findFieldByNumber(21).get)
            .flatMap(
              _.as[_root_.scala.Option[
                pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionWh
              ]]
            ),
          energyConsumptionWhSinceCharge = __fieldsMap
            .get(scalaDescriptor.findFieldByNumber(22).get)
            .flatMap(
              _.as[_root_.scala.Option[
                pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionWh
              ]]
            ),
          energyConsumptionPercentageManual = __fieldsMap
            .get(scalaDescriptor.findFieldByNumber(23).get)
            .flatMap(
              _.as[_root_.scala.Option[
                pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage
              ]]
            ),
          energyConsumptionPercentageAutomatic = __fieldsMap
            .get(scalaDescriptor.findFieldByNumber(24).get)
            .flatMap(
              _.as[_root_.scala.Option[
                pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage
              ]]
            ),
          energyConsumptionPercentageSinceCharge = __fieldsMap
            .get(scalaDescriptor.findFieldByNumber(25).get)
            .flatMap(
              _.as[_root_.scala.Option[
                pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage
              ]]
            ),
          chargerPowerStatus =
            pccs.vehiclestates.entities.battery.v1.battery.ChargerPowerStatus.fromValue(
              __fieldsMap
                .get(scalaDescriptor.findFieldByNumber(26).get)
                .map(_.as[_root_.scalapb.descriptors.EnumValueDescriptor])
                .getOrElse(
                  pccs.vehiclestates.entities.battery.v1.battery.ChargerPowerStatus.CHARGER_POWER_STATUS_UNSPECIFIED.scalaValueDescriptor
                )
                .number
            )
        )
      case _ => throw new RuntimeException("Expected PMessage")
    }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor =
    pccs.vehiclestates.entities.battery.v1.battery.BatteryProto.javaDescriptor
      .getMessageTypes()
      .get(2)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor =
    pccs.vehiclestates.entities.battery.v1.battery.BatteryProto.scalaDescriptor.messages(2)
  def messageCompanionForFieldNumber(
    __number: _root_.scala.Int
  ): _root_.scalapb.GeneratedMessageCompanion[?] =
    var __out: _root_.scalapb.GeneratedMessageCompanion[?] = null
    (__number: @ _root_.scala.unchecked) match
      case 1  => __out = pccs.vehiclestates.entities.common.v1.common.Timestamp
      case 20 => __out = pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionWh
      case 21 => __out = pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionWh
      case 22 => __out = pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionWh
      case 23 => __out = pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage
      case 24 => __out = pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage
      case 25 => __out = pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage
    __out
  lazy val nestedMessagesCompanions
    : Seq[_root_.scalapb.GeneratedMessageCompanion[? <: _root_.scalapb.GeneratedMessage]] =
    Seq.empty
  def enumCompanionForFieldNumber(
    __fieldNumber: _root_.scala.Int
  ): _root_.scalapb.GeneratedEnumCompanion[?] =
    (__fieldNumber: @ _root_.scala.unchecked) match
      case 6  => pccs.vehiclestates.entities.battery.v1.battery.ChargerConnectionStatus
      case 7  => pccs.vehiclestates.entities.battery.v1.battery.ChargingStatus
      case 17 => pccs.vehiclestates.entities.battery.v1.battery.ChargingType
      case 26 => pccs.vehiclestates.entities.battery.v1.battery.ChargerPowerStatus
  lazy val defaultInstance = pccs.vehiclestates.entities.battery.v1.battery.Battery(
    timestamp = _root_.scala.None,
    batteryChargeLevelPercentage = 0.0,
    averageEnergyConsumptionKwhPer100Km = 0.0,
    estimatedDistanceToEmptyKm = 0,
    estimatedChargingTimeToFullMinutes = 0,
    chargerConnectionStatus =
      pccs.vehiclestates.entities.battery.v1.battery.ChargerConnectionStatus.CHARGER_CONNECTION_STATUS_UNSPECIFIED,
    chargingStatus =
      pccs.vehiclestates.entities.battery.v1.battery.ChargingStatus.CHARGING_STATUS_UNSPECIFIED,
    estimatedDistanceToEmptyMiles = 0,
    estimatedChargingTimeMinutesToTargetDistance = 0,
    chargingPowerWatts = 0,
    chargingCurrentAmps = 0,
    averageEnergyConsumptionKwhPer100KmAutomatic = 0.0,
    averageEnergyConsumptionKwhPer100KmSinceCharge = 0.0,
    totalEnergyConsumptionWh = 0.0,
    totalEnergyConsumptionWhAutomatic = 0.0,
    totalEnergyConsumptionWhSinceCharge = 0.0,
    chargingType =
      pccs.vehiclestates.entities.battery.v1.battery.ChargingType.CHARGING_TYPE_UNSPECIFIED,
    chargingVoltageVolts = 0,
    estimatedChargingTimeMinutesToMinimumSoc = 0,
    energyConsumptionWhManual = _root_.scala.None,
    energyConsumptionWhAutomatic = _root_.scala.None,
    energyConsumptionWhSinceCharge = _root_.scala.None,
    energyConsumptionPercentageManual = _root_.scala.None,
    energyConsumptionPercentageAutomatic = _root_.scala.None,
    energyConsumptionPercentageSinceCharge = _root_.scala.None,
    chargerPowerStatus =
      pccs.vehiclestates.entities.battery.v1.battery.ChargerPowerStatus.CHARGER_POWER_STATUS_UNSPECIFIED
  )
  implicit class BatteryLens[UpperPB](
    _l: _root_.scalapb.lenses.Lens[UpperPB, pccs.vehiclestates.entities.battery.v1.battery.Battery]
  ) extends _root_.scalapb.lenses.ObjectLens[
      UpperPB,
      pccs.vehiclestates.entities.battery.v1.battery.Battery
    ](_l):
    def timestamp: _root_.scalapb.lenses.Lens[
      UpperPB,
      pccs.vehiclestates.entities.common.v1.common.Timestamp
    ] = field(_.getTimestamp)((c_, f_) => c_.copy(timestamp = _root_.scala.Option(f_)))
    def optionalTimestamp: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[
      pccs.vehiclestates.entities.common.v1.common.Timestamp
    ]] = field(_.timestamp)((c_, f_) => c_.copy(timestamp = f_))
    def batteryChargeLevelPercentage: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Double] =
      field(_.batteryChargeLevelPercentage)((c_, f_) => c_.copy(batteryChargeLevelPercentage = f_))
    def averageEnergyConsumptionKwhPer100Km
      : _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Double] = field(
      _.averageEnergyConsumptionKwhPer100Km
    )((c_, f_) => c_.copy(averageEnergyConsumptionKwhPer100Km = f_))
    def estimatedDistanceToEmptyKm: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Int] =
      field(_.estimatedDistanceToEmptyKm)((c_, f_) => c_.copy(estimatedDistanceToEmptyKm = f_))
    def estimatedChargingTimeToFullMinutes: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Int] =
      field(_.estimatedChargingTimeToFullMinutes)((c_, f_) =>
        c_.copy(estimatedChargingTimeToFullMinutes = f_)
      )
    def chargerConnectionStatus: _root_.scalapb.lenses.Lens[
      UpperPB,
      pccs.vehiclestates.entities.battery.v1.battery.ChargerConnectionStatus
    ] = field(_.chargerConnectionStatus)((c_, f_) => c_.copy(chargerConnectionStatus = f_))
    def chargingStatus: _root_.scalapb.lenses.Lens[
      UpperPB,
      pccs.vehiclestates.entities.battery.v1.battery.ChargingStatus
    ] = field(_.chargingStatus)((c_, f_) => c_.copy(chargingStatus = f_))
    def estimatedDistanceToEmptyMiles: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Int] =
      field(_.estimatedDistanceToEmptyMiles)((c_, f_) =>
        c_.copy(estimatedDistanceToEmptyMiles = f_)
      )
    def estimatedChargingTimeMinutesToTargetDistance
      : _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Int] = field(
      _.estimatedChargingTimeMinutesToTargetDistance
    )((c_, f_) => c_.copy(estimatedChargingTimeMinutesToTargetDistance = f_))
    def chargingPowerWatts: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Int] =
      field(_.chargingPowerWatts)((c_, f_) => c_.copy(chargingPowerWatts = f_))
    def chargingCurrentAmps: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Int] =
      field(_.chargingCurrentAmps)((c_, f_) => c_.copy(chargingCurrentAmps = f_))
    def averageEnergyConsumptionKwhPer100KmAutomatic
      : _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Double] = field(
      _.averageEnergyConsumptionKwhPer100KmAutomatic
    )((c_, f_) => c_.copy(averageEnergyConsumptionKwhPer100KmAutomatic = f_))
    def averageEnergyConsumptionKwhPer100KmSinceCharge
      : _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Double] = field(
      _.averageEnergyConsumptionKwhPer100KmSinceCharge
    )((c_, f_) => c_.copy(averageEnergyConsumptionKwhPer100KmSinceCharge = f_))
    def totalEnergyConsumptionWh: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Double] =
      field(_.totalEnergyConsumptionWh)((c_, f_) => c_.copy(totalEnergyConsumptionWh = f_))
    def totalEnergyConsumptionWhAutomatic
      : _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Double] = field(
      _.totalEnergyConsumptionWhAutomatic
    )((c_, f_) => c_.copy(totalEnergyConsumptionWhAutomatic = f_))
    def totalEnergyConsumptionWhSinceCharge
      : _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Double] = field(
      _.totalEnergyConsumptionWhSinceCharge
    )((c_, f_) => c_.copy(totalEnergyConsumptionWhSinceCharge = f_))
    def chargingType: _root_.scalapb.lenses.Lens[
      UpperPB,
      pccs.vehiclestates.entities.battery.v1.battery.ChargingType
    ] = field(_.chargingType)((c_, f_) => c_.copy(chargingType = f_))
    def chargingVoltageVolts: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Int] =
      field(_.chargingVoltageVolts)((c_, f_) => c_.copy(chargingVoltageVolts = f_))
    def estimatedChargingTimeMinutesToMinimumSoc
      : _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Int] = field(
      _.estimatedChargingTimeMinutesToMinimumSoc
    )((c_, f_) => c_.copy(estimatedChargingTimeMinutesToMinimumSoc = f_))
    def energyConsumptionWhManual: _root_.scalapb.lenses.Lens[
      UpperPB,
      pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionWh
    ] = field(_.getEnergyConsumptionWhManual)((c_, f_) =>
      c_.copy(energyConsumptionWhManual = _root_.scala.Option(f_))
    )
    def optionalEnergyConsumptionWhManual: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[
      pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionWh
    ]] = field(_.energyConsumptionWhManual)((c_, f_) => c_.copy(energyConsumptionWhManual = f_))
    def energyConsumptionWhAutomatic: _root_.scalapb.lenses.Lens[
      UpperPB,
      pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionWh
    ] = field(_.getEnergyConsumptionWhAutomatic)((c_, f_) =>
      c_.copy(energyConsumptionWhAutomatic = _root_.scala.Option(f_))
    )
    def optionalEnergyConsumptionWhAutomatic
      : _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[
        pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionWh
      ]] =
      field(_.energyConsumptionWhAutomatic)((c_, f_) => c_.copy(energyConsumptionWhAutomatic = f_))
    def energyConsumptionWhSinceCharge: _root_.scalapb.lenses.Lens[
      UpperPB,
      pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionWh
    ] = field(_.getEnergyConsumptionWhSinceCharge)((c_, f_) =>
      c_.copy(energyConsumptionWhSinceCharge = _root_.scala.Option(f_))
    )
    def optionalEnergyConsumptionWhSinceCharge
      : _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[
        pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionWh
      ]] = field(_.energyConsumptionWhSinceCharge)((c_, f_) =>
      c_.copy(energyConsumptionWhSinceCharge = f_)
    )
    def energyConsumptionPercentageManual: _root_.scalapb.lenses.Lens[
      UpperPB,
      pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage
    ] = field(_.getEnergyConsumptionPercentageManual)((c_, f_) =>
      c_.copy(energyConsumptionPercentageManual = _root_.scala.Option(f_))
    )
    def optionalEnergyConsumptionPercentageManual
      : _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[
        pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage
      ]] = field(_.energyConsumptionPercentageManual)((c_, f_) =>
      c_.copy(energyConsumptionPercentageManual = f_)
    )
    def energyConsumptionPercentageAutomatic: _root_.scalapb.lenses.Lens[
      UpperPB,
      pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage
    ] = field(_.getEnergyConsumptionPercentageAutomatic)((c_, f_) =>
      c_.copy(energyConsumptionPercentageAutomatic = _root_.scala.Option(f_))
    )
    def optionalEnergyConsumptionPercentageAutomatic
      : _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[
        pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage
      ]] = field(_.energyConsumptionPercentageAutomatic)((c_, f_) =>
      c_.copy(energyConsumptionPercentageAutomatic = f_)
    )
    def energyConsumptionPercentageSinceCharge: _root_.scalapb.lenses.Lens[
      UpperPB,
      pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage
    ] = field(_.getEnergyConsumptionPercentageSinceCharge)((c_, f_) =>
      c_.copy(energyConsumptionPercentageSinceCharge = _root_.scala.Option(f_))
    )
    def optionalEnergyConsumptionPercentageSinceCharge
      : _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[
        pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage
      ]] = field(_.energyConsumptionPercentageSinceCharge)((c_, f_) =>
      c_.copy(energyConsumptionPercentageSinceCharge = f_)
    )
    def chargerPowerStatus: _root_.scalapb.lenses.Lens[
      UpperPB,
      pccs.vehiclestates.entities.battery.v1.battery.ChargerPowerStatus
    ] = field(_.chargerPowerStatus)((c_, f_) => c_.copy(chargerPowerStatus = f_))
  final val TIMESTAMP_FIELD_NUMBER = 1
  final val BATTERY_CHARGE_LEVEL_PERCENTAGE_FIELD_NUMBER = 2
  final val AVERAGE_ENERGY_CONSUMPTION_KWH_PER_100_KM_FIELD_NUMBER = 3
  final val ESTIMATED_DISTANCE_TO_EMPTY_KM_FIELD_NUMBER = 4
  final val ESTIMATED_CHARGING_TIME_TO_FULL_MINUTES_FIELD_NUMBER = 5
  final val CHARGER_CONNECTION_STATUS_FIELD_NUMBER = 6
  final val CHARGING_STATUS_FIELD_NUMBER = 7
  final val ESTIMATED_DISTANCE_TO_EMPTY_MILES_FIELD_NUMBER = 8
  final val ESTIMATED_CHARGING_TIME_MINUTES_TO_TARGET_DISTANCE_FIELD_NUMBER = 9
  final val CHARGING_POWER_WATTS_FIELD_NUMBER = 10
  final val CHARGING_CURRENT_AMPS_FIELD_NUMBER = 11
  final val AVERAGE_ENERGY_CONSUMPTION_KWH_PER_100_KM_AUTOMATIC_FIELD_NUMBER = 12
  final val AVERAGE_ENERGY_CONSUMPTION_KWH_PER_100_KM_SINCE_CHARGE_FIELD_NUMBER = 13
  final val TOTAL_ENERGY_CONSUMPTION_WH_FIELD_NUMBER = 14
  final val TOTAL_ENERGY_CONSUMPTION_WH_AUTOMATIC_FIELD_NUMBER = 15
  final val TOTAL_ENERGY_CONSUMPTION_WH_SINCE_CHARGE_FIELD_NUMBER = 16
  final val CHARGING_TYPE_FIELD_NUMBER = 17
  final val CHARGING_VOLTAGE_VOLTS_FIELD_NUMBER = 18
  final val ESTIMATED_CHARGING_TIME_MINUTES_TO_MINIMUM_SOC_FIELD_NUMBER = 19
  final val ENERGY_CONSUMPTION_WH_MANUAL_FIELD_NUMBER = 20
  final val ENERGY_CONSUMPTION_WH_AUTOMATIC_FIELD_NUMBER = 21
  final val ENERGY_CONSUMPTION_WH_SINCE_CHARGE_FIELD_NUMBER = 22
  final val ENERGY_CONSUMPTION_PERCENTAGE_MANUAL_FIELD_NUMBER = 23
  final val ENERGY_CONSUMPTION_PERCENTAGE_AUTOMATIC_FIELD_NUMBER = 24
  final val ENERGY_CONSUMPTION_PERCENTAGE_SINCE_CHARGE_FIELD_NUMBER = 25
  final val CHARGER_POWER_STATUS_FIELD_NUMBER = 26
  def of(
    timestamp: _root_.scala.Option[pccs.vehiclestates.entities.common.v1.common.Timestamp],
    batteryChargeLevelPercentage: _root_.scala.Double,
    averageEnergyConsumptionKwhPer100Km: _root_.scala.Double,
    estimatedDistanceToEmptyKm: _root_.scala.Int,
    estimatedChargingTimeToFullMinutes: _root_.scala.Int,
    chargerConnectionStatus: pccs.vehiclestates.entities.battery.v1.battery.ChargerConnectionStatus,
    chargingStatus: pccs.vehiclestates.entities.battery.v1.battery.ChargingStatus,
    estimatedDistanceToEmptyMiles: _root_.scala.Int,
    estimatedChargingTimeMinutesToTargetDistance: _root_.scala.Int,
    chargingPowerWatts: _root_.scala.Int,
    chargingCurrentAmps: _root_.scala.Int,
    averageEnergyConsumptionKwhPer100KmAutomatic: _root_.scala.Double,
    averageEnergyConsumptionKwhPer100KmSinceCharge: _root_.scala.Double,
    totalEnergyConsumptionWh: _root_.scala.Double,
    totalEnergyConsumptionWhAutomatic: _root_.scala.Double,
    totalEnergyConsumptionWhSinceCharge: _root_.scala.Double,
    chargingType: pccs.vehiclestates.entities.battery.v1.battery.ChargingType,
    chargingVoltageVolts: _root_.scala.Int,
    estimatedChargingTimeMinutesToMinimumSoc: _root_.scala.Int,
    energyConsumptionWhManual: _root_.scala.Option[
      pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionWh
    ],
    energyConsumptionWhAutomatic: _root_.scala.Option[
      pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionWh
    ],
    energyConsumptionWhSinceCharge: _root_.scala.Option[
      pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionWh
    ],
    energyConsumptionPercentageManual: _root_.scala.Option[
      pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage
    ],
    energyConsumptionPercentageAutomatic: _root_.scala.Option[
      pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage
    ],
    energyConsumptionPercentageSinceCharge: _root_.scala.Option[
      pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage
    ],
    chargerPowerStatus: pccs.vehiclestates.entities.battery.v1.battery.ChargerPowerStatus
  ): _root_.pccs.vehiclestates.entities.battery.v1.battery.Battery =
    _root_.pccs.vehiclestates.entities.battery.v1.battery.Battery(
      timestamp,
      batteryChargeLevelPercentage,
      averageEnergyConsumptionKwhPer100Km,
      estimatedDistanceToEmptyKm,
      estimatedChargingTimeToFullMinutes,
      chargerConnectionStatus,
      chargingStatus,
      estimatedDistanceToEmptyMiles,
      estimatedChargingTimeMinutesToTargetDistance,
      chargingPowerWatts,
      chargingCurrentAmps,
      averageEnergyConsumptionKwhPer100KmAutomatic,
      averageEnergyConsumptionKwhPer100KmSinceCharge,
      totalEnergyConsumptionWh,
      totalEnergyConsumptionWhAutomatic,
      totalEnergyConsumptionWhSinceCharge,
      chargingType,
      chargingVoltageVolts,
      estimatedChargingTimeMinutesToMinimumSoc,
      energyConsumptionWhManual,
      energyConsumptionWhAutomatic,
      energyConsumptionWhSinceCharge,
      energyConsumptionPercentageManual,
      energyConsumptionPercentageAutomatic,
      energyConsumptionPercentageSinceCharge,
      chargerPowerStatus
    )
  // @@protoc_insertion_point(GeneratedMessageCompanion[pccs.vehiclestates.entities.battery.v1.Battery])
