// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package pccs.vehiclestates.entities.battery.v1.battery

sealed abstract class ChargerConnectionStatus(val value: _root_.scala.Int) extends _root_.scalapb.GeneratedEnum {
  type EnumType = pccs.vehiclestates.entities.battery.v1.battery.ChargerConnectionStatus
  type RecognizedType = pccs.vehiclestates.entities.battery.v1.battery.ChargerConnectionStatus.Recognized
  def isChargerConnectionStatusUnspecified: _root_.scala.Boolean = false
  def isChargerConnectionStatusConnected: _root_.scala.Boolean = false
  def isChargerConnectionStatusDisconnected: _root_.scala.Boolean = false
  def isChargerConnectionStatusFault: _root_.scala.Boolean = false
  def companion: _root_.scalapb.GeneratedEnumCompanion[ChargerConnectionStatus] = pccs.vehiclestates.entities.battery.v1.battery.ChargerConnectionStatus
  final def asRecognized: _root_.scala.Option[pccs.vehiclestates.entities.battery.v1.battery.ChargerConnectionStatus.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[pccs.vehiclestates.entities.battery.v1.battery.ChargerConnectionStatus.Recognized])
}

object ChargerConnectionStatus extends _root_.scalapb.GeneratedEnumCompanion[ChargerConnectionStatus] {
  sealed trait Recognized extends ChargerConnectionStatus
  implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[ChargerConnectionStatus] = this
  
  @SerialVersionUID(0L)
  case object CHARGER_CONNECTION_STATUS_UNSPECIFIED extends ChargerConnectionStatus(0) with ChargerConnectionStatus.Recognized {
    val index = 0
    val name = "CHARGER_CONNECTION_STATUS_UNSPECIFIED"
    override def isChargerConnectionStatusUnspecified: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object CHARGER_CONNECTION_STATUS_CONNECTED extends ChargerConnectionStatus(1) with ChargerConnectionStatus.Recognized {
    val index = 1
    val name = "CHARGER_CONNECTION_STATUS_CONNECTED"
    override def isChargerConnectionStatusConnected: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object CHARGER_CONNECTION_STATUS_DISCONNECTED extends ChargerConnectionStatus(2) with ChargerConnectionStatus.Recognized {
    val index = 2
    val name = "CHARGER_CONNECTION_STATUS_DISCONNECTED"
    override def isChargerConnectionStatusDisconnected: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object CHARGER_CONNECTION_STATUS_FAULT extends ChargerConnectionStatus(3) with ChargerConnectionStatus.Recognized {
    val index = 3
    val name = "CHARGER_CONNECTION_STATUS_FAULT"
    override def isChargerConnectionStatusFault: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  final case class Unrecognized(unrecognizedValue: _root_.scala.Int) extends ChargerConnectionStatus(unrecognizedValue) with _root_.scalapb.UnrecognizedEnum
  lazy val values: scala.collection.immutable.Seq[ValueType] = scala.collection.immutable.Seq(CHARGER_CONNECTION_STATUS_UNSPECIFIED, CHARGER_CONNECTION_STATUS_CONNECTED, CHARGER_CONNECTION_STATUS_DISCONNECTED, CHARGER_CONNECTION_STATUS_FAULT)
  def fromValue(__value: _root_.scala.Int): ChargerConnectionStatus = __value match {
    case 0 => CHARGER_CONNECTION_STATUS_UNSPECIFIED
    case 1 => CHARGER_CONNECTION_STATUS_CONNECTED
    case 2 => CHARGER_CONNECTION_STATUS_DISCONNECTED
    case 3 => CHARGER_CONNECTION_STATUS_FAULT
    case __other => Unrecognized(__other)
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = pccs.vehiclestates.entities.battery.v1.battery.BatteryProto.javaDescriptor.getEnumTypes().get(0)
  def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = pccs.vehiclestates.entities.battery.v1.battery.BatteryProto.scalaDescriptor.enums(0)
}