// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package pccs.vehiclestates.entities.battery.v1.battery

sealed abstract class ChargingType(val value: _root_.scala.Int)
  extends _root_.scalapb.GeneratedEnum:
  type EnumType = pccs.vehiclestates.entities.battery.v1.battery.ChargingType
  type RecognizedType = pccs.vehiclestates.entities.battery.v1.battery.ChargingType.Recognized
  def isChargingTypeUnspecified: _root_.scala.Boolean = false
  def isChargingTypeAc: _root_.scala.Boolean = false
  def isChargingTypeDc: _root_.scala.Boolean = false
  def companion: _root_.scalapb.GeneratedEnumCompanion[ChargingType] =
    pccs.vehiclestates.entities.battery.v1.battery.ChargingType
  final def asRecognized
    : _root_.scala.Option[pccs.vehiclestates.entities.battery.v1.battery.ChargingType.Recognized] =
    if isUnrecognized then _root_.scala.None
    else
      _root_.scala.Some(
        this.asInstanceOf[pccs.vehiclestates.entities.battery.v1.battery.ChargingType.Recognized]
      )

object ChargingType extends _root_.scalapb.GeneratedEnumCompanion[ChargingType]:
  sealed trait Recognized extends ChargingType
  implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[ChargingType] = this

  @SerialVersionUID(0L)
  case object CHARGING_TYPE_UNSPECIFIED extends ChargingType(0) with ChargingType.Recognized:
    val index = 0
    val name = "CHARGING_TYPE_UNSPECIFIED"
    override def isChargingTypeUnspecified: _root_.scala.Boolean = true

  @SerialVersionUID(0L)
  case object CHARGING_TYPE_AC extends ChargingType(1) with ChargingType.Recognized:
    val index = 1
    val name = "CHARGING_TYPE_AC"
    override def isChargingTypeAc: _root_.scala.Boolean = true

  @SerialVersionUID(0L)
  case object CHARGING_TYPE_DC extends ChargingType(2) with ChargingType.Recognized:
    val index = 2
    val name = "CHARGING_TYPE_DC"
    override def isChargingTypeDc: _root_.scala.Boolean = true

  @SerialVersionUID(0L)
  final case class Unrecognized(unrecognizedValue: _root_.scala.Int)
    extends ChargingType(unrecognizedValue)
    with _root_.scalapb.UnrecognizedEnum
  lazy val values: scala.collection.immutable.Seq[ValueType] =
    scala.collection.immutable.Seq(CHARGING_TYPE_UNSPECIFIED, CHARGING_TYPE_AC, CHARGING_TYPE_DC)
  def fromValue(__value: _root_.scala.Int): ChargingType = __value match
    case 0       => CHARGING_TYPE_UNSPECIFIED
    case 1       => CHARGING_TYPE_AC
    case 2       => CHARGING_TYPE_DC
    case __other => Unrecognized(__other)
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor =
    pccs.vehiclestates.entities.battery.v1.battery.BatteryProto.javaDescriptor.getEnumTypes().get(2)
  def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor =
    pccs.vehiclestates.entities.battery.v1.battery.BatteryProto.scalaDescriptor.enums(2)
