// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package pccs.vehiclestates.entities.battery.v1.battery

@SerialVersionUID(0L)
final case class EnergyConsumptionPercentage(
  value: _root_.scala.Double = 0.0,
  unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
) extends scalapb.GeneratedMessage
  with scalapb.lenses.Updatable[EnergyConsumptionPercentage]:
  @transient
  private var __serializedSizeMemoized: _root_.scala.Int = 0
  private def __computeSerializedSize(): _root_.scala.Int =
    var __size = 0

    {
      val __value = value
      if __value != 0.0 then
        __size += _root_.com.google.protobuf.CodedOutputStream.computeDoubleSize(1, __value)
    };
    __size += unknownFields.serializedSize
    __size
  override def serializedSize: _root_.scala.Int =
    var __size = __serializedSizeMemoized
    if __size == 0 then
      __size = __computeSerializedSize() + 1
      __serializedSizeMemoized = __size
    __size - 1

  def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit =
    {
      val __v = value
      if __v != 0.0 then _output__.writeDouble(1, __v)
    };
    unknownFields.writeTo(_output__)
  def withValue(__v: _root_.scala.Double): EnergyConsumptionPercentage = copy(value = __v)
  def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
  def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
  def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any =
    (__fieldNumber: @ _root_.scala.unchecked) match
      case 1 =>
        val __t = value
        if __t != 0.0 then __t else null
  def getField(
    __field: _root_.scalapb.descriptors.FieldDescriptor
  ): _root_.scalapb.descriptors.PValue =
    _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
    (__field.number: @ _root_.scala.unchecked) match
      case 1 => _root_.scalapb.descriptors.PDouble(value)
  def toProtoString: _root_.scala.Predef.String =
    _root_.scalapb.TextFormat.printToUnicodeString(this)
  def companion: pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage.type =
    pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage
  // @@protoc_insertion_point(GeneratedMessage[pccs.vehiclestates.entities.battery.v1.EnergyConsumptionPercentage])

object EnergyConsumptionPercentage
  extends scalapb.GeneratedMessageCompanion[
    pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage
  ]:
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[
    pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage
  ] = this
  def parseFrom(
    `_input__`: _root_.com.google.protobuf.CodedInputStream
  ): pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage =
    var __value: _root_.scala.Double = 0.0
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while !_done__ do
      val _tag__ = _input__.readTag()
      _tag__ match
        case 0 => _done__ = true
        case 9 =>
          __value = _input__.readDouble()
        case tag =>
          if _unknownFields__ == null then
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          _unknownFields__.parseField(tag, _input__)
    pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage(
      value = __value,
      unknownFields = if _unknownFields__ == null then _root_.scalapb.UnknownFieldSet.empty
      else _unknownFields__.result()
    )
  implicit def messageReads: _root_.scalapb.descriptors.Reads[
    pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage
  ] = _root_.scalapb.descriptors.Reads:
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(
        __fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor),
        "FieldDescriptor does not match message type."
      )
      pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage(
        value = __fieldsMap
          .get(scalaDescriptor.findFieldByNumber(1).get)
          .map(_.as[_root_.scala.Double])
          .getOrElse(0.0)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor =
    pccs.vehiclestates.entities.battery.v1.battery.BatteryProto.javaDescriptor
      .getMessageTypes()
      .get(0)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor =
    pccs.vehiclestates.entities.battery.v1.battery.BatteryProto.scalaDescriptor.messages(0)
  def messageCompanionForFieldNumber(
    __number: _root_.scala.Int
  ): _root_.scalapb.GeneratedMessageCompanion[?] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions
    : Seq[_root_.scalapb.GeneratedMessageCompanion[? <: _root_.scalapb.GeneratedMessage]] =
    Seq.empty
  def enumCompanionForFieldNumber(
    __fieldNumber: _root_.scala.Int
  ): _root_.scalapb.GeneratedEnumCompanion[?] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance =
    pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage(
      value = 0.0
    )
  implicit class EnergyConsumptionPercentageLens[UpperPB](
    _l: _root_.scalapb.lenses.Lens[
      UpperPB,
      pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage
    ]
  ) extends _root_.scalapb.lenses.ObjectLens[
      UpperPB,
      pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage
    ](_l):
    def value: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Double] =
      field(_.value)((c_, f_) => c_.copy(value = f_))
  final val VALUE_FIELD_NUMBER = 1
  def of(
    value: _root_.scala.Double
  ): _root_.pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage =
    _root_.pccs.vehiclestates.entities.battery.v1.battery.EnergyConsumptionPercentage(
      value
    )
  // @@protoc_insertion_point(GeneratedMessageCompanion[pccs.vehiclestates.entities.battery.v1.EnergyConsumptionPercentage])
