// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package pccs.chronos.messages.common.v1.chronos_request

object ChronosRequestProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    pccs.chronos.entities.common.v1.chronos_common.ChronosCommonProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      pccs.chronos.messages.common.v1.chronos_request.ChronosRequest
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """ChVjaHJvbm9zX3JlcXVlc3QucHJvdG8SH3BjY3MuY2hyb25vcy5tZXNzYWdlcy5jb21tb24udjEaFGNocm9ub3NfY29tbW9uL
  nByb3RvIsEBCg5DaHJvbm9zUmVxdWVzdBIXCgJpZBgBIAEoCUIH4j8EEgJpZFICaWQSGgoDdmluGAIgASgJQgjiPwUSA3ZpblIDd
  mluEiMKBnNvdXJjZRgDIAEoCUIL4j8IEgZzb3VyY2VSBnNvdXJjZRJVCgl0aW1lX3pvbmUYBCABKAsyKS5wY2NzLmNocm9ub3MuZ
  W50aXRpZXMuY29tbW9uLnYxLlRpbWVab25lQg3iPwoSCHRpbWVab25lUgh0aW1lWm9uZWIGcHJvdG8z"""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      pccs.chronos.entities.common.v1.chronos_common.ChronosCommonProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}