name: Test

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04

    services:
      mysql:
        image: mariadb:10.11.6
        env:
          MYSQL_DATABASE: testboat
          MYSQL_USER: testboat
          MYSQL_PASSWORD: testboat123
          MYSQL_ROOT_PASSWORD: testboat123
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
          cache: sbt
      - uses: sbt/setup-sbt@v1
      - name: Run utils tests
        run: sbt utils/test
      - name: Run agent tests
        run: sbt agent/test
      - name: Run backend tests
        env:
          DB_PASS: testboat123
        run: sbt boat/test
      - name: Run frontend tests
        run: sbt frontend/test
      - name: Run integration tests
        env:
          DB_PASS: testboat123
        run: sbt integration-tests/test
