name: Test

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up Scala
        uses: olafurpg/setup-scala@v11
        with:
          java-version: "adopt@1.11"
      - name: Run utils tests
        run: sbt utils/test
      - name: Run agent tests
        run: sbt agent/test
      - name: Run backend tests
        run: sbt boat/test
      - name: Run frontend tests
        run: sbt frontend/test
      - name: Run integration tests
        run: sbt integration-tests/test
