name: Test

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'sbt''
      - name: Run utils tests
        run: sbt utils/test
      - name: Run agent tests
        run: sbt agent/test
      - name: Run backend tests
        run: sbt boat/test
      - name: Run frontend tests
        run: sbt frontend/test
      - name: Run integration tests
        run: sbt integration-tests/test
