name: Test

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
          cache: sbt
      - uses: sbt/setup-sbt@v1
      - name: Run utils tests
        run: sbt utils/test
      - name: Run agent tests
        run: sbt agent/test
      - name: Run backend tests
        run: sbt boat/test
      - name: Run frontend tests
        run: sbt frontend/test
      - name: Run integration tests
        run: sbt integration-tests/test
