name: Deploy

on:
  push:
    branches:
      - master

env:
  AZURE_RG: rg-fnxr3ec3ms6mu
  AZURE_WEBAPP_NAME: boat-win-nuqmhn2cxlhle
  AZURE_WEBAPP_PACKAGE_PATH: ${{ github.workspace }}
  AZURE_SLOT: staging

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Login via Azure CLI
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
          cache: sbt
      - name: Build with sbt
        run: |
          ls -al
          sbt "mode prod" compile
          sbt "mode prod" boat/assembly
          ls -al
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v3
        with:
          type: jar
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: ${{ env.AZURE_SLOT }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/backend/target/scala-*/app.jar'
      - name: Azure logout
        run: |
          az logout
