name: Deploy

on:
  push:
    branches:
      - master

env:
  AZURE_RG: rg-fnxr3ec3ms6mu
  AZURE_WEBAPP_NAME: boat-win-nuqmhn2cxlhle
  AZURE_WEBAPP_PACKAGE_PATH: ${{ github.workspace }}
  AZURE_SLOT: staging

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set up Scala
        uses: olafurpg/setup-scala@v11
        with:
          java-version: "adopt@1.11"
      - name: Build with sbt
        run: |
          ls -al
          sbt "set scalaJSStage in Global := FullOptStage" compile
          sbt "set scalaJSStage in Global := FullOptStage" boat/assembly
          ls -al
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: ${{ env.AZURE_SLOT }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/backend/target/scala-*/app.jar'
      - name: Azure logout
        run: |
          az logout
